"""Screens of the account, notification, personal library, games and community areas."""
from fds_screens import AUTH, EX_SESSION, ex_menu, owner_only, role, screen

LEARNER = role("CUSTOMER")
SIGNED_IN = ("User is signed in with any canonical role", "Continue rendering", "Redirect → Login; GLB-01")
OWNER_RULE = ("BR-27", "Personal data is visible only to its owner",
              "Another user's id returns 404 → GLB-03; lists show only the user's own records")

SCREENS = [
    # ------------------------------------------------------------------ Profile & Account
    screen(
        key="Profile", name="Profile & Account", route="/account/profile", roles="Any signed-in role",
        ft="FT-05, FT-06", uc="UC: Manage profile and learning goal", status="Specified (OAuth linking: Draft)",
        purpose="Lets a user keep account details and the learner profile up to date and manage linked sign-in "
                "providers.",
        nav_from=[("Top bar avatar menu", "User clicks \"Profile\"")],
        nav_to=[("Learning Goals", "User clicks the \"Goals\" tab"), ("Login", "User signs out")],
        pre=[AUTH, SIGNED_IN],
        entry=[("Avatar menu", "Any screen", "—")],
        exits=[("User clicks Save account / Save profile", "API returns 200", "Stay", "MSG-01"),
               ("User clicks Unlink", "Confirmed", "Stay", "Identity removed from the list"),
               ex_menu("GLB-07 if a form has unsaved edits"), EX_SESSION],
        comps=[("TXT", "Full name", "Text Input", "Required; not blank; MSG-04", "Account section"),
               ("TXT", "Phone number", "Text Input", "Optional; unique across accounts; MSG-03", "Account section"),
               ("TXT", "Email", "Text (read-only)", "—", "Cannot be changed"),
               ("BTN", "Save account", "Button (Primary)", "—", "Triggers API 3"),
               ("TXT", "Display name", "Text Input", "Required; 1–100 chars (BV-01); MSG-05", "Profile section"),
               ("TXT", "Avatar URL", "Text Input", "Optional; ≤ 500 chars", "Preview thumbnail"),
               ("TXA", "Bio", "Text Area", "≤ 1,000 chars (BV-03); counter", "—"),
               ("NUM", "Current band", "Number (step 0.5)", "0.0–9.0 (BV-02); MSG-06", "—"),
               ("SEL", "Timezone", "Select", "IANA names, ≤ 50 chars", "Default: Asia/Ho_Chi_Minh"),
               ("RAD", "Profile visibility", "Radio group", "PUBLIC or PRIVATE", "Default: PRIVATE"),
               ("BTN", "Save profile", "Button (Primary)", "—", "Triggers API 4"),
               ("TBL", "Linked sign-in providers", "List", "—", "Provider, linked date; \"Unlink\" per row"),
               ("BTN", "Unlink", "Button (Danger)", "Requires confirm MSG-07", "Per provider")],
        apis=[("Page load (mount)", "user.me", "—", "Fill account section · loading: skeleton", "401 → GLB-01"),
              ("Page load (parallel)", "user.profile", "—", "Fill profile section", "404 → empty profile form"),
              ("User clicks Save account", "user.updateMe", "`{fullName, phoneNumber}`", "Toast MSG-01", "409 → MSG-03; "
               "400 → MSG-04"),
              ("User clicks Save profile", "user.updateProfile", "`{displayName, avatarReference, bio, selfReportedBand, "
               "timezone, visibility}`", "Toast MSG-01", "400 → MSG-05 / MSG-06"),
              ("Page load (parallel)", "user.oauth", "—", "Render providers", "Error → hide section"),
              ("User confirms Unlink", "user.unlinkOauth", "Path: `provider`", "Remove row; toast MSG-02",
               "404 → reload list")],
        interactions=[("Unlink guard", ["IF the user has no password sign-in and this is the only provider [TBC, OQ-02]",
                                        "THEN   disable Unlink with tooltip \"Set a password before unlinking\"",
                                        "END IF"])],
        msgs=[("Success Toast", "Save succeeded", "\"Your changes have been saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Provider unlinked", "\"The sign-in provider has been unlinked.\"", "Auto-dismiss 3s"),
              ("Inline Error", "409 phone in use", "\"This phone number is already used by another account.\"",
               "Below field, red colour"),
              ("Inline Error", "Full name blank", "\"Enter your full name.\"", "Below field, red colour"),
              ("Inline Error", "Display name invalid", "\"Enter a display name of up to 100 characters.\"",
               "Below field, red colour"),
              ("Inline Error", "Band outside 0–9", "\"Enter a band from 0.0 to 9.0.\"", "Below field, red colour"),
              ("Confirm Modal", "User clicks Unlink", "Title: \"Unlink {provider}?\" · Body: \"You will no longer be able "
               "to sign in with {provider}.\"", "Buttons: \"Unlink\" (Danger) + \"Cancel\"")],
        rules=[OWNER_RULE, ("FT-06 BV-01…03", "Display name ≤ 100, band 0–9, bio ≤ 1,000", "Inline errors MSG-05/06")],
    ),
    # ------------------------------------------------------------------ Learning Goals
    screen(
        key="Goals", name="Learning Goals", route="/account/goals", roles="CUSTOMER",
        ft="FT-09, FT-35", uc="UC: Manage profile and learning goal; Take placement test",
        status="Specified (edit of the active goal: Draft; the placement survey also saves a goal)",
        purpose="Lets the learner set one active goal — target band, exam date and daily study minutes — and pause, "
                "resume or close it, so progress can be tracked against a target.",
        nav_from=[("Course List", "User clicks \"Set a goal\" or the goal summary"),
                  ("Profile & Account", "User clicks the \"Goals\" tab")],
        nav_to=[("Placement Test", "User clicks \"Take the placement test\""),
                ("Course List", "Goal saved; user clicks \"Back to learning\"")],
        pre=[AUTH, LEARNER],
        entry=[("Set a goal", "Course List", "—"), ("Goals tab", "Profile & Account", "—")],
        exits=[("User clicks Save goal", "API returns 201/200", "Stay", "MSG-01"),
               ("User changes status", "Confirmed", "Stay", "MSG-02"), ex_menu("GLB-07 if unsaved"), EX_SESSION],
        comps=[("CRD", "Active goal", "Card", "—", "Target band, exam date, minutes/day, days left; status badge"),
               ("NUM", "Target band", "Number (step 0.5)", "Required; 1.0–9.0 (BV-01); MSG-04", "—"),
               ("DAT", "Exam date", "Date picker", "Optional; after today (BV-03); MSG-05", "—"),
               ("NUM", "Study minutes per day", "Number", "Required; ≥ 5 (BV-02); MSG-06", "Default: 30"),
               ("BTN", "Save goal", "Button (Primary)", "—", "Triggers API 3"),
               ("BTN", "Pause / Resume", "Button (Secondary)", "Pause when ACTIVE; Resume when PAUSED", "Triggers API 4"),
               ("BTN", "Mark achieved / Abandon", "Button (Secondary / Danger)", "Confirm MSG-07", "Triggers API 4"),
               ("TBL", "Goal history", "Table", "Newest first", "Band, exam date, status, created"),
               ("LNK", "Take the placement test", "Link", "Hidden once the placement is taken", "Opens /learn/placement")],
        apis=[("Page load (mount)", "goal.active", "—", "Fill active card · loading: skeleton", "404 → empty state MSG-03"),
              ("Page load (parallel)", "goal.list", "—", "Render history", "Error → GLB-04"),
              ("User clicks Save goal", "goal.create", "`{targetBand, examDate, availableMinutesPerDay}`",
               "Toast MSG-01; reload API 1 and 2", "400 → MSG-04…06; 409 (concurrent) → reload"),
              ("User changes status", "goal.status", "Path: `goalId`; `{status}` (ACTIVE, PAUSED, ACHIEVED, ABANDONED)",
               "Toast MSG-02; reload", "400 → MSG-08")],
        interactions=[("Saving while a goal is ACTIVE", [
            "Target (FT-09): saving updates the ACTIVE goal (same id).",
            "Current release: a goal cannot be edited; saving creates a new ACTIVE goal and moves the",
            "previous one to PAUSED. The form explains this with an info line until the edit API exists."])],
        msgs=[("Success Toast", "Goal saved", "\"Your goal has been saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Status changed", "\"Goal status updated.\"", "Auto-dismiss 3s"),
              ("Empty State", "No active goal", "Title: \"Set your IELTS goal\" · Description: \"Choose a target band and "
               "how long you can study each day.\"", "CTA: \"Set a goal\""),
              ("Inline Error", "Band outside 1.0–9.0", "\"Choose a target band from 1.0 to 9.0.\"", "Below field"),
              ("Inline Error", "Exam date today or past", "\"Choose an exam date after today.\"", "Below field"),
              ("Inline Error", "Minutes below 5", "\"Plan at least 5 minutes a day.\"", "Below field"),
              ("Confirm Modal", "Mark achieved / Abandon", "Title: \"Close this goal?\" · Body: \"You can set a new goal "
               "afterwards.\"", "Buttons: \"Confirm\" + \"Cancel\""),
              ("Error Toast", "Invalid status change", "\"This goal cannot be changed that way.\"", "Auto-dismiss 5s")],
        rules=[("BR-05", "At most one ACTIVE goal", "Server enforces; screen shows a single active card"),
               ("FT-09 BV-01…03", "Band 1–9, minutes ≥ 5, exam date after today", "Inline errors MSG-04…06")],
    ),
    # ------------------------------------------------------------------ Subscription & Points
    screen(
        key="Wallet", name="Subscription & Points", route="/account/subscription", roles="CUSTOMER",
        ft="FT-10, FT-11, FT-12, FT-14", uc="UC: View subscription; View points; Activate key", status="Specified",
        fe="partial",
        frontend="Partly built — no account page. The point balance is shown in the user menu (UserTierDropdown, "
                 "from access.myPoints after sign-in and after each essay); the Premium/Free badge there is a demo "
                 "toggle (GAP-04); keys are redeemed only from the Home dialog (GAP-03). The rest is the design target.",
        purpose="Shows the learner's subscription, examiner credits, point balance and history, and lets the learner "
                "redeem an activation key for Premium days or points.",
        nav_from=[("Top bar points badge", "User clicks the balance"), ("Writing Feedback", "User clicks \"Top up points\""),
                  ("Course Path", "User clicks \"Unlock with Premium\" [Draft]")],
        nav_to=[("Previous screen", "User clicks \"Back\" after redeeming")],
        pre=[AUTH, LEARNER],
        entry=[("Points badge", "Top bar", "—"), ("Top up link", "Writing Feedback", "Query: `?activate=1` (opens MDL-01)")],
        exits=[("User redeems a key", "API returns 200", "Stay", "MSG-01 / MSG-02"), ex_menu(), EX_SESSION],
        comps=[("CRD", "Subscription", "Card", "—", "Plan, status ACTIVE / EXPIRED / CANCELLED, end date, examiner "
                "credits left; \"No subscription\" state"),
               ("CRD", "Point balance", "Card", "—", "Whole number ≥ 0"),
               ("TBL", "Points history", "Table", "20 per page (offset/limit)", "Date, type (KEY_CREDIT, "
                "AI_GRADING_DEBIT, AI_GRADING_REFUND, ADMIN_ADJUSTMENT), amount ±, balance after"),
               ("BTN", "Activate a key", "Button (Primary)", "—", "Opens MDL-01"),
               ("MDL", "Activate key", "Modal", "—", "Holds TXT-01 and BTN-02"),
               ("TXT", "Activation key", "Text Input", "Required; trimmed; upper-cased; MSG-05", "Placeholder: \"XXXX-XXXX-XXXX\""),
               ("BTN", "Redeem", "Button (Primary)", "Disabled while empty or pending", "Triggers API 4")],
        apis=[("Page load (mount)", "access.mySub", "—", "Fill subscription card · loading: skeleton", "404 → \"No "
               "subscription\""),
              ("Page load (parallel)", "access.myPoints", "—", "Fill balance", "404 → balance 0"),
              ("Page load / page change", "access.myHistory", "Query: `offset, limit=20`", "Render rows", "Error → GLB-04"),
              ("User clicks Redeem", "access.activate", "`{rawKey, idempotencyKey}` (idempotencyKey generated when the "
               "modal opens, reused on retry)", "Close modal; toast MSG-01 or MSG-02; reload API 1–3",
               "400 → MSG-03; 404 → MSG-04")],
        interactions=[("Redeem result", [
            "IF product type = PREMIUM   → MSG-01 with the new end date (+ credits added)",
            "ELSE (POINTS)               → MSG-02 with the points added",
            "END IF",
            "A repeat with the same idempotencyKey returns the first result; the screen shows it the same way."])],
        msgs=[("Success Toast", "Premium key redeemed", "\"Premium is active until {endDate}.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Points key redeemed", "\"{points} points have been added to your balance.\"",
               "Auto-dismiss 3s"),
              ("Inline Error", "400 (redeemed, revoked, expired)", "\"This key has already been used, was cancelled or has "
               "expired. Ask your centre for a new key.\"", "Below field, red colour"),
              ("Inline Error", "404", "\"We could not find this key. Check it and try again.\"", "Below field, red colour"),
              ("Inline Error", "Blank key", "\"Enter your activation key.\"", "Below field, red colour"),
              ("Empty State", "No ledger entries", "Title: \"No points activity yet\" · Description: \"Redeem a points key "
               "to get started.\"", "CTA: \"Activate a key\"")],
        rules=[("BR-07", "A key is redeemed at most once", "MSG-03"),
               ("BR-08", "Premium days extend the active subscription", "MSG-01 shows the new end date"),
               ("BR-09", "Balance never below 0; every change in the ledger", "History table"),
               ("BR-30", "Same idempotencyKey grants once", "Key reused on network retry")],
    ),
    # ------------------------------------------------------------------ Activity & Streak
    screen(
        key="Activity", name="Activity & Streak", route="/account/activity", roles="Any signed-in role",
        ft="FT-44, FT-45", uc="UC: View activity and streak", status="Specified (server-side streak: Draft)",
        purpose="Shows the learner's study activities and current and longest streak, so the learner can keep a "
                "daily study habit.",
        nav_from=[("Top bar streak badge", "User clicks the flame badge"), ("Main menu", "User clicks \"Activity\"")],
        nav_to=[("Course List", "User clicks \"Study now\"")],
        pre=[AUTH, SIGNED_IN],
        entry=[("Streak badge", "Top bar", "—"), ("Main menu", "Any screen", "—")],
        exits=[("User deletes an activity", "Confirmed", "Stay", "MSG-02"), ex_menu(), EX_SESSION],
        comps=[("CRD", "Current streak", "Card", "≥ 0 days", "Flame icon; last qualifying date"),
               ("CRD", "Longest streak", "Card", "≥ 0 days", "—"),
               ("TBL", "Activities", "Table", "20 per page", "Type, source, date, duration (min)"),
               ("BTN", "Delete", "Button (Danger)", "Confirm MSG-03", "Per row")],
        apis=[("Page load (mount)", "streak.get", "—", "Fill cards", "404 → zeros"),
              ("Page load / page change", "activity.list", "Query: `page, size=20`", "Render table · loading: skeleton",
               "Error → GLB-04"),
              ("Learner finishes a study action on another screen", "activity.create", "`{activityType, sourceType, "
               "sourceId, occurredAt, durationSeconds}`", "Silent; no UI on this screen", "400 → ignored, logged"),
              ("Activity recorded (client-side streak, current release)", "streak.put", "`{currentDays, longestDays, "
               "lastQualifiedDate, timezone}`", "Silent", "400 → ignored"),
              ("User confirms Delete", "activity.delete", "Path: `id`", "Remove row; toast MSG-02", "404 → reload")],
        interactions=[("Client-side streak (current release)", [
            "On the first qualifying activity of a local day (profile timezone):",
            "IF lastQualifiedDate = yesterday THEN currentDays + 1",
            "ELSE IF lastQualifiedDate = today THEN no change",
            "ELSE currentDays = 1",
            "END IF; longestDays = max(longestDays, currentDays); then streak.put.",
            "Target: the server calculates the streak (FT-45 Draft) and this logic is removed."])],
        msgs=[("Empty State", "No activity", "Title: \"No study activity yet\" · Description: \"Finish a lesson or practice "
               "set to start your streak.\"", "CTA: \"Study now\""),
              ("Success Toast", "Activity deleted", "\"Activity removed.\"", "Auto-dismiss 3s"),
              ("Confirm Modal", "User clicks Delete", "Title: \"Remove this activity?\" · Body: \"Your streak is not "
               "recalculated.\"", "Buttons: \"Remove\" (Danger) + \"Cancel\"")],
        rules=[OWNER_RULE, ("FT-45 BV-01", "Day counts ≥ 0", "Client never sends negative values")],
    ),
    # ------------------------------------------------------------------ Notification Centre
    screen(
        key="Notifications", name="Notification Centre", route="/notifications", roles="CUSTOMER",
        ft="FT-51, FT-52, FT-53, FT-54", uc="UC: Manage notification preferences; Receive study reminders and "
                                           "grading-done alerts", status="Draft",
        draft="Draft: notification-service is a skeleton with a reserved route and no API; every API row below is "
              "[TBC] (OQ-10).",
        purpose="Lists the learner's in-app notifications and lets the learner choose channels, reminder time and "
                "registered devices.",
        nav_from=[("Top bar bell", "User clicks the bell"), ("Push notification", "User taps a push message")],
        nav_to=[("Test Result", "User opens a grading-done notification"),
                ("Course List", "User opens a study reminder")],
        pre=[AUTH, LEARNER],
        entry=[("Bell icon", "Top bar", "—"), ("Push tap", "Device", "Query: `?notificationId=`")],
        exits=[("User clicks a notification", "Has a target", "Target screen", "Marked read"), ex_menu(), EX_SESSION],
        comps=[("TAB", "Tabs", "Tab bar", "Notifications, Preferences, Devices", "—"),
               ("TBL", "Notifications", "List", "Newest first; 20 per page", "Unread in bold; time; link"),
               ("BTN", "Mark as read", "Button (Tertiary)", "—", "Per item"),
               ("CHK", "Channel toggles", "Toggle", "One per channel [TBC: PUSH, EMAIL, IN_APP]", "—"),
               ("SEL", "Reminder time", "Time picker", "Local time", "Uses profile timezone"),
               ("TBL", "Devices", "List", "—", "Platform, last seen; \"Revoke\" per row"),
               ("BTN", "Revoke device", "Button (Danger)", "Confirm MSG-03", "—")],
        apis=[("Notifications tab load", "notif.list", "Query: `page, size`", "Render list", "Error → GLB-04"),
              ("User clicks a notification / Mark as read", "notif.read", "Path: `id`", "Bold removed; badge count - 1",
               "404 → reload"),
              ("Preferences tab load", "notif.prefs", "—", "Fill toggles", "Error → GLB-04"),
              ("Toggle or time changed", "notif.savePrefs", "Path: `channel`; `{enabled, preferredTime, timezone}`",
               "Toast MSG-01", "400 → GLB-06"),
              ("App start with push permission", "notif.registerDevice", "Path: `installationId`; `{platform, pushToken}`",
               "Silent (same installation updates its token)", "Error → retry next start"),
              ("Devices tab load", "notif.devices", "—", "Render devices", "Error → GLB-04"),
              ("User confirms Revoke", "notif.revokeDevice", "Path: `installationId`", "Remove row; MSG-02", "404 → reload")],
        interactions=[("Unread badge", ["Bell badge = unread count from notif.list; refreshed on page focus [TBC: push "
                                        "or polling]."])],
        msgs=[("Success Toast", "Preference saved", "\"Notification settings saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Device revoked", "\"This device will no longer receive notifications.\"", "Auto-dismiss 3s"),
              ("Confirm Modal", "User clicks Revoke", "Title: \"Stop notifications on this device?\"",
               "Buttons: \"Revoke\" (Danger) + \"Cancel\""),
              ("Empty State", "No notifications", "Title: \"You're all caught up\"", "—")],
        rules=[("BR-32", "One preference per channel; at most one reminder a day", "Toggles, not a list"),
               OWNER_RULE],
    ),
    # ------------------------------------------------------------------ Vocabulary
    screen(
        key="Vocabulary", name="Vocabulary", route="/vocabulary · Public page", roles="Guest and any signed-in user",
        ft="FT-36, FT-43", uc="UC: Browse vocabulary and videos; Manage notes and flashcards", fe="mock",
        status="Specified (backend); frontend on mock data (GAP-10)",
        frontend="Built on mock data — features/vocabulary/pages/VocabularyPage.tsx with VocabularyCollection and "
                 "mocks/lessonData.ts (LESSON_VOCABULARY); search, pronunciation and save work in the page only. The "
                 "design target calls library-service (rows below).",
        shots=[("Vocabulary.png", "Vocabulary (/vocabulary) — mock word list")],
        purpose="Lets the learner look up topic vocabulary, hear the pronunciation and save words to review later.",
        nav_from=[("Top bar", "User opens \"Sổ từ vựng\" → \"Kho từ vựng\""), ("Classroom Lesson Workspace", "Homework Hub / Từ vựng")],
        nav_to=[("Flashcards & Decks", "Design target: user opens saved words")],
        pre=[("None — public page", "Render", "—")],
        entry=[("Top bar", "Any page", "—")],
        exits=[("User picks another top bar item", "Any", "Selected route", "Saved words are lost (page state)")],
        comps=[("PNL", "Header", "Banner", "—", "\"IELTS SPACE DICTIONARY\" · \"Từ điển học theo chủ đề\" · \"Tra cứu, nghe phát "
                "âm và lưu lại từ cần ôn.\" · \"{n} từ\""),
               ("TXT", "Tìm từ vựng", "Search Input", "Matches word, meaning or topic", "Placeholder \"Tìm từ, nghĩa hoặc chủ "
                "đề\"; \"{n} từ phù hợp\""),
               ("CRD", "Word card", "Card list", "—", "Word, part of speech, CEFR level, UK/US IPA, definition, Vietnamese "
                "meaning, tags, example, \"Hình ảnh gợi nhớ\""),
               ("BTN", "Nghe phát âm từ {word}", "Icon button", "Browser speech synthesis", "—"),
               ("BTN", "Lưu / Bỏ lưu", "Toggle button", "—", "Page state only (GAP-10)")],
        apis=[("Page load / search", None, "mocks/lessonData.ts", "Filter words in memory", "—"),
              ("Design target: search typed", "vocab.search", "Query: `query`", "Render results", "Error → GLB-04"),
              ("Design target: user opens a word", "vocab.get", "Path: `id`", "Render senses", "404 → GLB-03"),
              ("Design target: user clicks Lưu", "card.create", "`{sourceType: VOCABULARY_SENSE, vocabularySenseId, front, "
               "back}`", "Saved state", "400 → GLB-06")],
        interactions=[("Pronunciation", ["IF the browser has speech synthesis THEN speak the word and announce \"Đang phát "
                                         "cách đọc: {word}.\" then \"Đã phát cách đọc: {word}.\"",
                                         "ELSE show MSG-02"])],
        msgs=[("Empty State", "No word matches", "\"Không tìm thấy từ phù hợp. Hãy thử một từ khóa khác.\"", "—"),
              ("Inline Error", "No speech support", "\"Thiết bị này chưa hỗ trợ phát âm thanh.\" / \"Không thể phát âm thanh trên "
               "thiết bị này.\"", "Live region")],
        rules=[("BR-27", "Catalog writes need ADMIN or CONTENT_AUTHOR", "No edit controls on this screen"),
               ("GAP-10", "Saved words are not stored in library-service", "Lost on reload")],
    ),
    # ------------------------------------------------------------------ Video Library
    screen(
        key="VideoLibrary", name="Video Library", route="/library/videos", roles="CUSTOMER, EXAMINER, CONTENT_AUTHOR, ADMIN",
        ft="FT-37, FT-38", uc="UC: Browse vocabulary and videos", status="Specified",
        purpose="Lists the published learning videos with the learner's progress, so the learner can pick one to "
                "watch.",
        nav_from=[("Main menu", "User clicks \"Videos\"")],
        nav_to=[("Video Player", "User clicks a video")],
        pre=[AUTH, role("ADMIN, CONTENT_AUTHOR, CUSTOMER or EXAMINER")],
        entry=[("Main menu", "Any learner screen", "Query: `?level=B1`")],
        exits=[("User clicks a video", "Any", "Video Player", "—"), ex_menu(), EX_SESSION],
        comps=[("SEL", "Level filter", "Select", "All, A2, B1, B2, C1, C2", "Client-side filter on the loaded page"),
               ("SEL", "Access filter", "Select", "All, FREE, PREMIUM", "Sent as accessLevel"),
               ("CRD", "Video card", "Card grid", "—", "Thumbnail, title, duration, level"),
               ("PRG", "Watch progress", "Progress bar", "0–100%", "From the learner's video progress")],
        apis=[("Page load / filter change", "video.list", "Query: `accessLevel, status=PUBLISHED`", "Render cards · "
               "loading: skeleton", "Error → GLB-04"),
              ("Page load (parallel)", "progress.list", "Query: `page, size=100`", "Join progress by videoId in memory",
               "Error → hide bars")],
        interactions=[("Progress join", ["Progress records are loaded once and joined by videoId; no request per card."])],
        msgs=[("Empty State", "No video", "Title: \"No videos yet\" · Description: \"New videos are added regularly.\"", "—")],
        rules=[("BR-27", "Progress visible only to its owner", "Bars use the learner's own records")],
    ),
    # ------------------------------------------------------------------ Video Player
    screen(
        key="VideoPlayer", name="Video Player", route="/library/videos/:videoId", roles="CUSTOMER",
        ft="FT-37, FT-38, FT-39, FT-40, FT-41", uc="UC: Track video progress and saved segments; Practise shadowing; "
                                                    "Practise dictation; Submit Speaking recording; Assess speech",
        status="Specified (shadowing / dictation scoring: Draft)",
        purpose="Plays a learning video with its segment transcript, remembers progress, saves segments and lets the "
                "learner practise shadowing and dictation on a segment.",
        nav_from=[("Video Library", "User clicks a video")],
        nav_to=[("Video Library", "User clicks \"Back\""), ("Flashcards & Decks", "User opens saved words")],
        pre=[AUTH, LEARNER, ("Video exists and is published", "Continue", "404 → Video Library; GLB-03")],
        entry=[("Video card", "Video Library", "`videoId`")],
        exits=[("User clicks Back", "Any", "Video Library", "Progress saved first"), EX_SESSION],
        comps=[("VID", "Player", "YouTube embed", "—", "Resumes at lastPositionMs"),
               ("TBL", "Segments", "Transcript list", "Ordered by sequenceNo", "Click → seek to startMs; highlighted "
                "words open the sense"),
               ("BTN", "Save segment", "Button (Secondary)", "Note ≤ 2,000 chars; MSG-04", "Per segment; opens note field"),
               ("TBL", "Saved segments", "List", "—", "Delete per row"),
               ("BTN", "Shadow this segment", "Button (Secondary)", "Draft: recording", "Creates a SHADOWING attempt"),
               ("BTN", "Record / Stop", "Button (Primary)", "Duration [TBC]; MSG-05", "Draft"),
               ("TXA", "Dictation answer", "Text Area", "Required [TBC]", "DICTATION attempt; audio replay allowed"),
               ("CRD", "Speech scores", "Card", "Draft", "Transcript, pronunciation, fluency (FT-39)")],
        apis=[("Page load (mount)", "video.get", "Path: `videoId`", "Render player and segments · loading: skeleton",
               "404 → GLB-03"),
              ("Every 15 s while playing, on pause and on leave", "progress.put", "`{videoId, lastPositionMs, "
               "watchedDurationSeconds, progressPercent, status}`", "Silent", "400 → ignored, logged"),
              ("User clicks Save segment", "segment.save", "`{videoId, segmentId, transcriptSnapshot, note}`",
               "Add to saved list; toast MSG-01", "400 → MSG-04"),
              ("Page load (parallel)", "segment.list", "Query: `page, size`", "Saved list (filtered to this video)", "—"),
              ("User deletes a saved segment", "segment.delete", "Path: `id`", "Remove row", "404 → reload"),
              ("User starts shadowing / dictation", "as.videoPractice", "`{videoId, segmentId, practiceType, "
               "referenceTextSnapshot}`", "Attempt created", "400 → GLB-06"),
              ("User stops recording [Draft]", "as.recording", "audio file + attempt id [TBC]", "Show scores MSG-02 "
               "(within [TBC] s)", "Provider failure → MSG-03"),
              ("User submits dictation [Draft]", "as.dictation", "`{text}` [TBC]", "Show % correct and missed words",
               "Empty → MSG-06")],
        interactions=[("Progress status", ["progressPercent ≥ 95 → status COMPLETED; > 0 → IN_PROGRESS [TBC: threshold]."]),
                      ("Snapshot", ["The practice attempt stores the segment's text at start, so later edits of the video",
                                    "do not change the attempt (FT-40)."])],
        msgs=[("Success Toast", "Segment saved", "\"Segment saved to your library.\"", "Auto-dismiss 3s"),
              ("Info Toast", "Scores ready [Draft]", "\"Your recording has been scored.\"", "Auto-dismiss 3s"),
              ("Error Toast", "Provider failure [Draft]", "\"We could not score this recording. Please try again.\"",
               "Auto-dismiss 5s"),
              ("Inline Error", "Note over 2,000 chars", "\"Keep your note under 2,000 characters.\"", "Below field"),
              ("Inline Error", "Recording too long/short [Draft]", "\"Recordings must be {min}–{max} seconds.\"",
               "Below recorder"),
              ("Inline Error", "Empty dictation [Draft]", "\"Type what you heard before checking.\"", "Below field")],
        rules=[OWNER_RULE, ("FT-38 BV-01", "Progress 0–100%", "Client clamps before sending"),
               ("BR-30", "Speech scoring resend does not duplicate [Draft]", "Same attempt id on retry")],
    ),
    # ------------------------------------------------------------------ My Notes
    screen(
        key="Notes", name="My Notes", route="/library/notes", roles="Any signed-in role",
        ft="FT-42", uc="UC: Manage notes and flashcards", status="Specified",
        purpose="Lets the learner write private notes, optionally linked to a knowledge point or a Reading section.",
        nav_from=[("Main menu", "User clicks \"Notes\""), ("Lesson Player / Review Session", "User clicks \"Add note\" "
                                                                                           "(source prefilled)")],
        nav_to=[("Lesson Player", "User clicks the note's source link [TBC: resolve lesson from KP]")],
        pre=[AUTH, SIGNED_IN],
        entry=[("Main menu", "Any screen", "—"), ("Add note", "Lesson Player", "Query: `?sourceType=KNOWLEDGE_POINT&"
                                                                              "sourceReferenceId=`")],
        exits=[("Save", "API 2xx", "Stay", "MSG-01"), ex_menu("GLB-07 if the editor has unsaved text"), EX_SESSION],
        comps=[("TBL", "Notes list", "List", "20 per page; filter by source", "Title, updated, source tag"),
               ("TXT", "Title", "Text Input", "Required; ≤ 255 chars; MSG-03", "—"),
               ("TXA", "Body", "Text Area", "Required; ≤ 20,000 chars; MSG-04", "Counter"),
               ("SEL", "Source type", "Select", "None, KNOWLEDGE_POINT, READING, TUTOR_SESSION", "Requires a source id "
                "when set (MSG-05)"),
               ("BTN", "Save", "Button (Primary)", "—", "Create or update"),
               ("BTN", "Delete", "Button (Danger)", "Confirm MSG-06", "—")],
        apis=[("Page load / filter", "note.list", "Query: `status=ACTIVE, page, size, sourceType, sourceReferenceId`",
               "Render list", "Error → GLB-04"),
              ("User opens a note", "note.get", "Path: `id`", "Fill editor", "404 → GLB-03"),
              ("User clicks Save (new)", "note.create", "`{title, body, sourceType, sourceReferenceId}`", "Toast MSG-01",
               "400 → MSG-03…05"),
              ("User clicks Save (existing)", "note.update", "Path: `id`; `{title, body, status}`", "Toast MSG-01",
               "400 → MSG-03/04"),
              ("User confirms Delete", "note.delete", "Path: `id`", "Remove from list; toast MSG-02", "404 → reload"),
              ("Note linked to READING", "content.reading", "Path: `sectionId`", "Show the passage title as source",
               "Error → show \"Reading section\"")],
        interactions=[("Source pair", ["sourceType and sourceReferenceId are sent together or not at all (FT-42/NAC-01)."])],
        msgs=[("Success Toast", "Saved", "\"Note saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Deleted", "\"Note deleted.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Title invalid", "\"Enter a title of up to 255 characters.\"", "Below field"),
              ("Inline Error", "Body invalid", "\"Write your note (up to 20,000 characters).\"", "Below field"),
              ("Inline Error", "Source incomplete", "\"Choose what this note is about, or remove the link.\"",
               "Below field"),
              ("Confirm Modal", "Delete", "Title: \"Delete this note?\"", "Buttons: \"Delete\" (Danger) + \"Cancel\"")],
        rules=[OWNER_RULE, ("FT-42 BV-01/02", "Title ≤ 255, body ≤ 20,000", "Inline errors")],
    ),
    # ------------------------------------------------------------------ Flashcards & Decks
    screen(
        key="Flashcards", name="Flashcards & Decks", route="/library/flashcards", roles="Any signed-in role",
        ft="FT-43", uc="UC: Manage notes and flashcards", status="Specified",
        purpose="Lets the learner create flashcards, group them into decks and study a deck card by card.",
        nav_from=[("Top bar", "User opens \"Sổ từ vựng\" → \"Flashcard của tôi\" (/flashcards shows a placeholder page today)"), ("Vocabulary / Practice Set", "Card saved; user opens the "
                                                                                           "library")],
        nav_to=[("Vocabulary", "User clicks a VOCABULARY_SENSE card's source")],
        pre=[AUTH, SIGNED_IN],
        entry=[("Main menu", "Any screen", "Query: `?deckId=`")],
        exits=[("Save / add / remove", "API 2xx", "Stay", "MSG-01"), ex_menu(), EX_SESSION],
        comps=[("TAB", "Tabs", "Tab bar", "Cards, Decks, Study", "—"),
               ("TBL", "Cards", "List", "20 per page; status ACTIVE", "Front, back preview, source type"),
               ("TXA", "Front", "Text Area", "Required; ≤ 4,000 chars; MSG-03", "—"),
               ("TXA", "Back", "Text Area", "Required; ≤ 4,000 chars; MSG-03", "—"),
               ("TXT", "Highlighted text", "Text Input", "Optional; ≤ 2,000 chars", "—"),
               ("TBL", "Decks", "List", "20 per page", "Name, card count"),
               ("TXT", "Deck name", "Text Input", "Required; ≤ 150 chars; MSG-04", "—"),
               ("TXA", "Deck description", "Text Area", "≤ 2,000 chars", "—"),
               ("SEL", "Add to deck", "Select", "Learner's decks", "Per card"),
               ("CRD", "Study card", "Flip card", "—", "Click to flip; next / previous")],
        apis=[("Cards tab", "card.list", "Query: `status=ACTIVE, page, size`", "Render cards", "Error → GLB-04"),
              ("Save card", "card.create", "`{sourceType: MANUAL, front, back, highlightedText}`", "Toast MSG-01",
               "400 → MSG-03"),
              ("Edit card", "card.update", "Path: `id`; same fields + status", "Toast MSG-01", "404 → reload"),
              ("Delete card", "card.delete", "Path: `id`", "Toast MSG-02", "404 → reload"),
              ("Decks tab", "deck.list", "Query: `status=ACTIVE, page, size`", "Render decks", "Error → GLB-04"),
              ("Save deck", "deck.create", "`{name, description}`", "Toast MSG-01", "400 → MSG-04"),
              ("Rename / archive deck", "deck.update", "Path: `id`; `{name, description, status}`", "Toast MSG-01",
               "404 → reload"),
              ("Delete deck", "deck.delete", "Path: `id`", "Toast MSG-02", "404 → reload"),
              ("Add card to deck", "deck.addItem", "Path: `deckId`; `{flashcardId, sortOrder}`", "Toast MSG-05",
               "404 → reload"),
              ("Open deck / Study", "deck.items", "Path: `deckId`; Query: `page, size`", "Render cards", "404 → GLB-03"),
              ("Remove card from deck", "deck.removeItem", "Path: `deckId, flashcardId`", "Card stays in Cards tab",
               "404 → reload")],
        interactions=[("Remove vs delete", ["Removing from a deck keeps the card (FT-43/AC-02); deleting a card removes "
                                            "it everywhere and needs confirm MSG-06."])],
        msgs=[("Success Toast", "Saved", "\"Saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Deleted", "\"Deleted.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Front/back invalid", "\"Fill in both sides (up to 4,000 characters each).\"", "Below field"),
              ("Inline Error", "Deck name invalid", "\"Enter a deck name of up to 150 characters.\"", "Below field"),
              ("Success Toast", "Added to deck", "\"Card added to {deck}.\"", "Auto-dismiss 3s"),
              ("Confirm Modal", "Delete card or deck", "Title: \"Delete this {card|deck}?\" · Body: \"This cannot be "
               "undone.\"", "Buttons: \"Delete\" (Danger) + \"Cancel\"")],
        rules=[OWNER_RULE, ("FT-43 BV-01/02", "Sides ≤ 4,000; deck name ≤ 150", "Inline errors")],
    ),
    # ------------------------------------------------------------------ Game Lobby
    screen(
        key="GameLobby", name="Game Lobby", route="/games", roles="Any signed-in role",
        ft="FT-46, FT-47, FT-48", uc="UC: Play game", status="Specified (matchmaking: Draft)",
        purpose="Lets the learner start a single-player game, create or join a multiplayer room, and see past "
                "sessions.",
        nav_from=[("Main menu", "User clicks \"Games\"")],
        nav_to=[("Single-player Game", "Session started"), ("Game Room", "Room created or joined")],
        pre=[AUTH, SIGNED_IN],
        entry=[("Main menu", "Any screen", "Query: `?code=ABC123` (join link)")],
        exits=[("User clicks Play", "Session created", "Single-player Game", "—"),
               ("User creates / joins a room", "API 2xx", "Game Room", "—"),
               ("User clicks Find a match [Draft]", "Queue joined", "Stay (waiting state)", "MSG-05"), ex_menu(), EX_SESSION],
        comps=[("SEL", "Game type", "Select", "WORD_MEANING_MATCH, SPELLING (VOCABULARY); SENTENCE_COMPLETION, "
                "ERROR_CORRECTION, WORD_ORDER (GRAMMAR)", "Domain is set from the type"),
               ("SEL", "Content source", "Select", "Topic, deck or vocabulary list → 1–20 content ids", "MSG-03"),
               ("BTN", "Play", "Button (Primary)", "—", "Triggers API 1"),
               ("NUM", "Max players", "Number", "2–32 (BV-01); MSG-04", "Default: 8"),
               ("BTN", "Create room", "Button (Secondary)", "—", "Triggers API 2"),
               ("TXT", "Room code", "Text Input", "Required for join", "—"),
               ("BTN", "Join", "Button (Secondary)", "—", "Triggers API 3"),
               ("BTN", "Find a match", "Button (Secondary)", "Draft", "Joins the matchmaking queue"),
               ("TBL", "History", "Table", "20 per page", "Game type, score, status COMPLETED / ABANDONED, date")],
        apis=[("User clicks Play", "game.start", "`{gameType, learningDomain, mode: PRACTICE, topicId, contentIds}`",
               "Navigate Single-player Game", "400 → MSG-02/03; 503 → GLB-05"),
              ("User clicks Create room", "room.create", "`{gameType, learningDomain, mode, maxPlayers, contentIds}`",
               "Navigate Game Room", "400 → MSG-04"),
              ("User clicks Join", "room.joinByCode", "Path: `roomCode`", "Navigate Game Room", "400 (full / not WAITING) "
               "→ MSG-01; 404 → MSG-06"),
              ("Lobby opened with `?code=` (join link)", "room.byCode", "Path: `roomCode`", "Show room preview (game "
               "type, players, status) with a Join button", "404 → MSG-06"),
              ("User clicks Join on the preview", "room.join", "Path: `roomId`", "Navigate Game Room",
               "400 (full / not WAITING) → MSG-01"),
              ("Page load", "game.history", "Query: `page, size=20`", "Render history", "Error → GLB-04"),
              ("User clicks Find a match [Draft]", "game.queue", "`{gameType, learningDomain}` [TBC]", "Waiting state; "
               "match found → Game Room", "Timeout → MSG-05")],
        interactions=[("Domain from type", ["VOCABULARY types fetch content from library, GRAMMAR types from content;",
                                            "the screen sets learningDomain from the chosen type so they never mismatch."])],
        msgs=[("Error Toast", "Room full or already started", "\"This room is full or the match has already started.\"",
               "Auto-dismiss 5s"),
              ("Error Toast", "Type/domain not supported", "\"This game cannot use that content. Choose another source.\"",
               "Auto-dismiss 5s"),
              ("Inline Error", "0 or > 20 items", "\"Choose between 1 and 20 items to play.\"", "Below field"),
              ("Inline Error", "Players outside 2–32", "\"A room holds 2 to 32 players.\"", "Below field"),
              ("Info Banner", "Matchmaking waiting / timeout [Draft]", "\"Looking for players…\" / \"No match found. "
               "Please try again.\"", "Persistent while waiting"),
              ("Error Toast", "Room code not found", "\"We could not find a room with this code.\"", "Auto-dismiss 5s")],
        rules=[("BR-29", "1 point per correct answer; room 2–32 players", "MSG-04"),
               ("FT-46 BV-01", "1–20 content ids per session", "MSG-03")],
    ),
    # ------------------------------------------------------------------ Single-player Game
    screen(
        key="SoloGame", name="Single-player Game", route="/games/sessions/:sessionId", roles="Any signed-in role",
        ft="FT-46", uc="UC: Play game", status="Specified",
        purpose="Plays a single-player vocabulary or grammar game item by item on a frozen content snapshot and shows "
                "the final score.",
        nav_from=[("Game Lobby", "Session started")],
        nav_to=[("Game Lobby", "Game finished or abandoned")],
        pre=[AUTH, SIGNED_IN, owner_only("game session")],
        entry=[("Play", "Game Lobby", "`sessionId`")],
        exits=[("Last item answered", "Session COMPLETED", "Stay (score panel)", "MSG-01"),
               ("User clicks Quit", "Confirmed", "Game Lobby", "Session ABANDONED (MSG-02)"), EX_SESSION],
        comps=[("PRG", "Item progress", "Progress", "item n of N", "—"),
               ("PNL", "Prompt", "Panel", "—", "From the snapshot item"),
               ("RAD", "Answer", "Choice / Text / Drag order", "Per game type", "Timer measures durationMilliseconds"),
               ("BTN", "Submit answer", "Button (Primary)", "Once per item", "Triggers API 2"),
               ("CRD", "Score", "Card", "—", "Live score; final score panel"),
               ("BTN", "Quit", "Button (Secondary)", "Confirm MSG-02", "Triggers API 3")],
        apis=[("Page load (mount)", "game.session", "Path: `sessionId`", "Render current item", "404 → GLB-03"),
              ("User submits an answer", "game.answer", "Path: `sessionId, itemSequence`; `{responsePayload, "
               "durationMilliseconds}`", "Show correct/incorrect, +1 when correct; next item", "400 (answered twice, "
               "ended) → reload session"),
              ("User confirms Quit / leaves the page", "game.abandon", "Path: `sessionId`", "Navigate Game Lobby",
               "Error → navigate anyway")],
        interactions=[("Leaving", ["Closing the tab or navigating away sends game.abandon (sendBeacon) so the session "
                                   "ends ABANDONED and is not counted as completed."])],
        msgs=[("Success Toast", "Session COMPLETED", "\"Game over — you scored {score} of {total}!\"", "Auto-dismiss 3s"),
              ("Confirm Modal", "User clicks Quit", "Title: \"Quit this game?\" · Body: \"Your progress will not count as "
               "a completed game.\"", "Buttons: \"Quit\" (Danger) + \"Keep playing\"")],
        rules=[("BR-29", "1 point per correct answer", "Score card"),
               ("FT-46/NAC-03", "Each item answered once", "Submit disabled after answering")],
    ),
    # ------------------------------------------------------------------ Game Room
    screen(
        key="GameRoom", name="Game Room", route="/games/rooms/:roomId", roles="Any signed-in role",
        ft="FT-47", uc="UC: Play game", status="Specified",
        purpose="Gathers players in a multiplayer room, lets the host start the match and plays it in real time over "
                "WebSocket, ending with a ranking.",
        nav_from=[("Game Lobby", "Room created or joined"), ("Join link", "Lobby opened with a room code")],
        nav_to=[("Game Lobby", "User leaves, host closes the room, or match ends")],
        pre=[AUTH, SIGNED_IN, ("User is a member of the room", "Continue", "Redirect → Game Lobby; GLB-03")],
        entry=[("Create / join", "Game Lobby", "`roomId`")],
        exits=[("User clicks Leave", "Any", "Game Lobby", "room.leave; MEMBER_LEFT broadcast"),
               ("Host clicks Close room", "Host only", "Game Lobby (all members)", "MSG-03"),
               ("Match ends", "All items played", "Stay (ranking)", "MSG-04"), EX_SESSION],
        comps=[("TBL", "Members", "List", "2–32", "Name, ready ✓, host crown"),
               ("CHK", "Ready", "Toggle", "—", "Sends READY over WebSocket (or API 3)"),
               ("BTN", "Start match", "Button (Primary)", "Host only; enabled when ≥ 2 active members are all ready",
                "Sends START_MATCH"),
               ("BTN", "Close room", "Button (Danger)", "Host only; confirm MSG-05", "Triggers API 5"),
               ("TXT", "Room code", "Text (copy)", "—", "Copy button + share link"),
               ("PNL", "Match item", "Panel", "—", "Prompt + answer input"),
               ("TBL", "Ranking", "Table", "Score desc, then total answer time asc", "Rank, player, score, time"),
               ("BDG", "Connection", "Badge", "Connected / Reconnecting…", "—")],
        apis=[("Page load (mount)", "room.get", "Path: `roomId`", "Render members", "404 → GLB-03"),
              ("After load", "room.ticket", "Path: `roomId`", "Ticket valid 30 s → API 7 immediately", "Error → GLB-05"),
              ("Ready toggled (fallback)", "room.ready", "`{ready}`", "Member list updates", "400 → reload"),
              ("User clicks Leave", "room.leave", "Path: `roomId`", "Navigate Game Lobby", "—"),
              ("Host confirms Close", "room.close", "Path: `roomId`", "All members return to lobby", "400 (not host) → GLB-02"),
              ("Match ended", "game.match", "Path: `matchId`", "Render ranking", "—"),
              ("Ticket received", "room.ws", "Subprotocols `game.v1`, `ticket.{ticket}`; messages PING, ROOM_STATE, "
               "READY, START_MATCH, ANSWER, LEAVE, RECONNECT", "CONNECTED, ROOM_STATE, MEMBER_LEFT, match events",
               "Handshake refused → new ticket, retry ×3 → MSG-06")],
        interactions=[("Reconnect", [
            "IF the socket closes during a match",
            "THEN   request a new ticket (room.ticket), reconnect, send RECONNECT {matchId}",
            "       show badge \"Reconnecting…\"; after 3 failures show MSG-06",
            "END IF"]),
            ("Start rule", ["Start is enabled only for the host and only when at least 2 active members are ready;",
                            "the server re-checks and replies ERROR otherwise (FT-47/NAC-01)."])],
        msgs=[("Info Toast", "Member joined / left", "\"{name} joined the room.\" / \"{name} left the room.\"",
               "Auto-dismiss 3s"),
              ("Warning Toast", "Start refused", "\"Everyone must be ready, with at least 2 players, to start.\"",
               "Auto-dismiss 5s"),
              ("Info Banner", "Room closed by host", "\"The host closed this room.\"", "Redirect after 3 s"),
              ("Success Toast", "Match ended", "\"Match over! You finished #{rank}.\"", "Auto-dismiss 3s"),
              ("Confirm Modal", "Host clicks Close room", "Title: \"Close this room?\" · Body: \"All players will be "
               "removed.\"", "Buttons: \"Close room\" (Danger) + \"Cancel\""),
              ("Alert Banner", "Cannot connect", "\"Connection lost. Check your internet and rejoin the room.\"",
               "Persistent; button \"Rejoin\"")],
        rules=[("BR-29", "Room 2–32 players; host starts once ≥ 2 members are ready", "Start disabled; MSG-02"),
               ("FT-47 BV-02", "WebSocket ticket valid 30 s", "Ticket requested right before connecting")],
    ),
    # ------------------------------------------------------------------ Community Feed
    screen(
        key="Feed", name="Community Feed", route="/community", roles="Any signed-in role",
        ft="FT-49, FT-50", uc="UC: Post and comment; Moderate community", status="Specified",
        purpose="Lists active community posts newest first and lets users write a post, react, and — for "
                "Administrators — hide posts that break the rules.",
        nav_from=[("Main menu", "User clicks \"Community\"")],
        nav_to=[("Post Detail", "User clicks a post")],
        pre=[AUTH, SIGNED_IN],
        entry=[("Main menu", "Any screen", "Query: `?page=`")],
        exits=[("User publishes a post", "API 201", "Stay (post on top)", "MSG-01"),
               ("User clicks a post", "Any", "Post Detail", "—"), ex_menu("GLB-07 if the composer has text"), EX_SESSION],
        comps=[("SEL", "Category", "Select", "GENERAL, QUESTION, DISCUSSION", "Default: GENERAL"),
               ("TXT", "Title", "Text Input", "Optional; ≤ 200 chars", "—"),
               ("TXA", "Body", "Text Area", "Required; 1–20,000 chars; MSG-03", "Counter"),
               ("BTN", "Publish", "Button (Primary)", "Disabled while body empty", "Triggers API 2"),
               ("CRD", "Post card", "Card list", "20 per page (1–100)", "Author id/name [TBC], category, excerpt, "
                "reaction counts, comment count"),
               ("BTN", "Like / Love", "Toggle button", "—", "Adds or removes the user's reaction"),
               ("BTN", "Hide", "Button (Danger)", "ADMIN only; confirm MSG-04", "Moderation"),
               ("BTN", "Load more", "Button (Secondary)", "—", "Next page")],
        apis=[("Page load / Load more", "post.list", "Query: `page, size=20`", "Append cards · loading: skeleton",
               "400 (size) → reset; error → GLB-04"),
              ("User clicks Publish", "post.create", "`{category, title, body}`", "Prepend card; toast MSG-01",
               "400 → MSG-03"),
              ("User toggles a reaction on", "post.react", "Path: `postId, type`", "Optimistic +1", "Error → revert"),
              ("User toggles a reaction off", "post.unreact", "Path: `postId, type`", "Optimistic −1", "Error → revert"),
              ("Admin confirms Hide", "post.moderate", "Path: `id`; `{status: HIDDEN}`", "Remove card; toast MSG-02",
               "403 → GLB-02; 400 (DELETED) → reload")],
        interactions=[("Reactions", ["Adding the same reaction twice has no effect on the server, so the optimistic "
                                     "update is safe to repeat."])],
        msgs=[("Success Toast", "Post published", "\"Your post is live.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Post hidden", "\"The post has been hidden.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Body empty or too long", "\"Write your post (up to 20,000 characters).\"", "Below field"),
              ("Confirm Modal", "Admin clicks Hide", "Title: \"Hide this post?\" · Body: \"It will disappear from the "
               "feed until you restore it.\"", "Buttons: \"Hide\" (Danger) + \"Cancel\""),
              ("Empty State", "No posts", "Title: \"No posts yet\" · Description: \"Be the first to share a tip.\"", "—")],
        rules=[("BR-28", "Own content only; soft delete; ADMIN hides/restores", "Edit/delete only on own cards; Hide only "
                "for ADMIN"),
               ("FT-49 BV-03", "Page size 1–100, default 20", "Client always sends 20")],
    ),
    # ------------------------------------------------------------------ Post Detail
    screen(
        key="Post", name="Post Detail", route="/community/posts/:postId", roles="Any signed-in role",
        ft="FT-49, FT-50", uc="UC: Post and comment; Moderate community", status="Specified",
        purpose="Shows one post with its comments and lets users comment, reply, edit or delete their own content, "
                "and Administrators hide or restore it.",
        nav_from=[("Community Feed", "User clicks a post")],
        nav_to=[("Community Feed", "Back, or the post was deleted / hidden")],
        pre=[AUTH, SIGNED_IN, ("Post is ACTIVE (or user is ADMIN)", "Continue", "404 → Community Feed; GLB-03")],
        entry=[("Post card", "Community Feed", "`postId`")],
        exits=[("Author deletes the post", "Confirmed", "Community Feed", "MSG-02"), EX_SESSION],
        comps=[("PNL", "Post", "Panel", "—", "Full body, category, reactions"),
               ("BTN", "Edit / Delete post", "Button", "Author only, ACTIVE only; delete confirm MSG-04", "—"),
               ("TBL", "Comments", "Flat list", "Oldest first; reply shows parent", "—"),
               ("TXA", "Comment", "Text Area", "Required; 1–5,000 chars; MSG-03", "Reply sets parentCommentId"),
               ("BTN", "Send", "Button (Primary)", "Disabled while empty", "Triggers API 3"),
               ("BTN", "Edit / Delete comment", "Button", "Author only", "—"),
               ("BTN", "Hide / Restore", "Button (Danger)", "ADMIN only; not for DELETED", "Post or comment")],
        apis=[("Page load (mount)", "post.get", "Path: `postId`", "Render post · loading: skeleton", "404 → GLB-03"),
              ("Page load (parallel)", "comment.list", "Path: `postId`; Query: `page, size`", "Render comments", "—"),
              ("User clicks Send", "comment.create", "Path: `postId`; `{parentCommentId, body}`", "Append comment",
               "400 → MSG-03"),
              ("Author saves an edit", "post.edit", "Path: `id`; `{category, title, body}`", "Toast MSG-01",
               "403 → GLB-02; 409 (concurrent edit) → MSG-05"),
              ("Author confirms Delete post", "post.delete", "Path: `id`", "Navigate Feed; MSG-02", "403 → GLB-02"),
              ("Author edits a comment", "comment.edit", "Path: `id`; `{body}`", "Update", "403 → GLB-02"),
              ("Author deletes a comment", "comment.delete", "Path: `id`", "Remove", "403 → GLB-02"),
              ("Admin hides / restores the post", "post.moderate", "`{status: HIDDEN | ACTIVE}`", "Badge update",
               "400 (DELETED) → MSG-06"),
              ("Admin hides / restores a comment", "comment.moderate", "`{status: HIDDEN | ACTIVE}`", "Update", "400 → MSG-06")],
        interactions=[("Control visibility", ["IF current user = author AND status = ACTIVE THEN show Edit/Delete",
                                              "IF user has ADMIN THEN show Hide (ACTIVE) or Restore (HIDDEN)",
                                              "END IF"])],
        msgs=[("Success Toast", "Saved", "\"Your changes have been saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Deleted", "\"Deleted.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Comment invalid", "\"Write a comment (up to 5,000 characters).\"", "Below field"),
              ("Confirm Modal", "Delete", "Title: \"Delete this post?\" · Body: \"It will be removed from the community.\"",
               "Buttons: \"Delete\" (Danger) + \"Cancel\""),
              ("Error Toast", "409 concurrent edit", "\"This post was changed by someone else. Reload to see the latest "
               "version.\"", "Auto-dismiss 5s"),
              ("Error Toast", "Moderating DELETED content", "\"Deleted content cannot be hidden or restored.\"",
               "Auto-dismiss 5s")],
        rules=[("BR-28", "Own content only; soft delete; ADMIN hides/restores non-deleted content", "Controls per role"),
               ("FT-49 BV-02", "Comment 1–5,000 chars", "MSG-03")],
    ),
]
