"""Screens of administration, sales, authoring and examiner grading (not built in the frontend yet)."""
from fds_screens import AUTH, EX_SESSION, ex_menu, role, screen

ADMIN = role("ADMIN")
AUTHOR = role("ADMIN or CONTENT_AUTHOR")
AUTHOR_RULE = ("BR-27 / FT-07", "Catalog writes need ADMIN or CONTENT_AUTHOR",
               "Route guarded (GG-02); API 403 → GLB-02")

SCREENS = [
    # ------------------------------------------------------------------ User Management
    screen(
        key="AdminUsers", name="User Management", route="/admin/users · ADMIN home", roles="ADMIN",
        ft="FT-07, FT-08", uc="UC: Manage users and roles", status="Specified (paging and search: Draft)",
        purpose="Lets an Administrator find accounts, create staff or learner accounts with roles, and open an account "
                "to manage it.",
        nav_from=[("Login", "Administrator signs in (ADMIN home)"), ("Main menu", "User clicks \"Users\"")],
        nav_to=[("User Detail", "User clicks a row or creates a user")],
        pre=[AUTH, ADMIN],
        entry=[("Sign-in as ADMIN", "Login", "—"), ("Main menu", "Any admin screen", "Query: `?role=&status=&q=`")],
        exits=[("User clicks a row", "Any", "User Detail", "—"),
               ("User saves a new user", "API 201", "User Detail", "MSG-01"), ex_menu(), EX_SESSION],
        comps=[("TXT", "Search", "Search Input", "Email, name or phone", "Client-side filter until server search "
                "exists (OQ-16)"),
               ("SEL", "Role filter", "Select", "All + five canonical roles", "—"),
               ("SEL", "Status filter", "Select", "All, ACTIVE, INACTIVE, LOCKED, PENDING_VERIFY", "—"),
               ("TBL", "Users", "Table", "Sortable: email, created; 20 rows per page (client paging)", "Email, full name, "
                "roles, status"),
               ("BTN", "Create user", "Button (Primary)", "—", "Opens MDL-01"),
               ("MDL", "Create user", "Modal", "—", "Fields below"),
               ("TXT", "Email", "Email Input", "Required; valid; unique (409 → MSG-02)", "—"),
               ("TXT", "Temporary password", "Password Input", "Required; 6–72 chars; MSG-03", "Generate button"),
               ("TXT", "Full name", "Text Input", "Required", "—"),
               ("CHK", "Roles", "Checkbox group", "At least one of the five roles; MSG-04", "Default: CUSTOMER"),
               ("BTN", "Save", "Button (Primary)", "—", "Triggers API 2")],
        apis=[("Page load (mount)", "admin.users", "—", "Render table · loading: skeleton", "403 → GLB-02"),
              ("User clicks Save", "admin.createUser", "`{email, password, fullName, phoneNumber, roles}`",
               "Toast MSG-01 · navigate User Detail", "409 → MSG-02; 400 → MSG-03/04")],
        interactions=[("List size", ["GET /api/users returns every user (no paging, FT-08 baseline). The table pages and",
                                     "filters in the browser; replace with server paging before the user count grows "
                                     "(OQ-16)."])],
        msgs=[("Success Toast", "User created", "\"User {email} has been created.\"", "Auto-dismiss 3s"),
              ("Inline Error", "409 email in use", "\"This email already belongs to an account.\"", "Below field"),
              ("Inline Error", "Password length", "\"Use 6 to 72 characters.\"", "Below field"),
              ("Inline Error", "No role / unknown role", "\"Choose at least one role.\"", "Below field"),
              ("Empty State", "No match", "Title: \"No users match these filters\"", "CTA: \"Clear filters\"")],
        rules=[("BR-06", "Only ADMIN manages users and roles; five canonical roles", "Route guarded; checkboxes limited to "
                "the five roles"),
               ("FT-08 BV-01", "1–5 distinct roles", "MSG-04")],
    ),
    # ------------------------------------------------------------------ User Detail
    screen(
        key="AdminUser", name="User Detail", route="/admin/users/:userId", roles="ADMIN",
        ft="FT-04, FT-05, FT-08, FT-09, FT-10, FT-12, FT-13", uc="UC: Manage users and roles",
        status="Specified",
        purpose="Lets an Administrator change one account's details, roles and status, and review its profile, goals, "
                "linked providers and account action tokens.",
        nav_from=[("User Management", "User clicks a row or created a user")],
        nav_to=[("User Management", "User clicks \"Back\" or deletes the account"),
                ("Points & Subscriptions", "User clicks \"Manage points & subscription\"")],
        pre=[AUTH, ADMIN, ("User id exists", "Continue", "404 → User Management; GLB-03")],
        entry=[("Row click / create", "User Management", "`userId`")],
        exits=[("Save details / roles / status", "API 200", "Stay", "MSG-01"),
               ("Delete account", "Confirmed", "User Management", "MSG-02"), ex_menu("GLB-07 if unsaved"), EX_SESSION],
        comps=[("TAB", "Sections", "Tab bar", "Account, Profile, Goals, Sign-in, Access", "—"),
               ("TXT", "Full name / Phone", "Text Input", "Full name required; phone unique (409)", "—"),
               ("CHK", "Roles", "Checkbox group", "1–5 canonical roles", "Note: \"Takes effect at the user's next sign-in "
                "or refresh\""),
               ("SEL", "Status", "Select", "ACTIVE, INACTIVE, LOCKED, PENDING_VERIFY", "Confirm MSG-03 when not ACTIVE"),
               ("BTN", "Save", "Button (Primary)", "—", "Per section"),
               ("BTN", "Delete account", "Button (Danger)", "Confirm MSG-04", "—"),
               ("PNL", "Profile", "Form", "Same rules as Profile & Account", "Editable by ADMIN"),
               ("TBL", "Goals", "Table", "—", "Status change per row"),
               ("TBL", "Linked providers", "List", "—", "Unlink per row"),
               ("TBL", "Account action tokens", "Table", "—", "Purpose, created, expiry, used; \"Revoke all\""),
               ("CRD", "Entitlement", "Card", "—", "Feature keys of the active plan (Access tab)")],
        apis=[("Page load (mount)", "admin.user", "Path: `userId`", "Fill Account tab · loading: skeleton", "404 → GLB-03"),
              ("Save account", "admin.updateUser", "`{fullName, phoneNumber}`", "Toast MSG-01", "409 → MSG-05"),
              ("Save roles", "admin.roles", "`{roles}`", "Toast MSG-01", "400 → MSG-06"),
              ("Save status", "admin.status", "`{status}`", "Toast MSG-01", "400 → GLB-06"),
              ("Confirm delete", "admin.deleteUser", "Path: `userId`", "Navigate list; MSG-02", "404 → list"),
              ("Profile tab", "admin.profile", "—", "Fill form", "404 → empty"),
              ("Save profile", "admin.updateProfile", "Profile fields", "Toast MSG-01", "400 → GLB-06"),
              ("Confirm delete profile", "admin.deleteProfile", "Path: `userId`", "Empty profile form; toast "
               "\"Learner profile deleted\"", "404 → empty"),
              ("Goals tab", "admin.goals", "—", "Render goals", "—"),
              ("Goal status change", "admin.goalStatus", "Path: `goalId`; `{status}`", "Reload goals", "400 → GLB-06"),
              ("Sign-in tab", "admin.oauth", "—", "Render providers", "—"),
              ("Unlink provider", "admin.unlinkOauth", "Path: `provider`", "Remove row", "404 → reload"),
              ("Sign-in tab", "admin.tokens", "—", "Render tokens", "—"),
              ("Revoke all tokens", "admin.revokeTokens", "—", "Reload tokens", "—"),
              ("Access tab", "access.entitlement", "Path: `userId`", "Render feature keys", "404 → \"No active plan\"")],
        interactions=[("Status effect", ["A status other than ACTIVE blocks the next sign-in and refresh; tokens already "
                                         "issued", "stay valid up to 3,600 s. The confirm modal says so (MSG-03)."])],
        msgs=[("Success Toast", "Saved", "\"Changes saved.\"", "Auto-dismiss 3s"),
              ("Success Toast", "Deleted", "\"The account has been deleted.\"", "Auto-dismiss 3s"),
              ("Confirm Modal", "Status → INACTIVE / LOCKED / PENDING_VERIFY", "Title: \"Change status to {status}?\" · "
               "Body: \"The user cannot sign in or refresh. A session already open ends within one hour.\"",
               "Buttons: \"Change status\" (Danger) + \"Cancel\""),
              ("Confirm Modal", "Delete account", "Title: \"Delete this account?\" · Body: \"This cannot be undone.\"",
               "Buttons: \"Delete\" (Danger) + \"Cancel\""),
              ("Inline Error", "409 phone", "\"This phone number is used by another account.\"", "Below field"),
              ("Inline Error", "Roles invalid", "\"Choose at least one role.\"", "Below field")],
        rules=[("BR-06", "ADMIN only", "Route guarded"),
               ("FT-08", "New roles/status apply at next token", "Note under Roles; MSG-03")],
    ),
    # ------------------------------------------------------------------ Plans & Key Products
    screen(
        key="Plans", name="Plans & Key Products", route="/admin/access/plans", roles="ADMIN",
        ft="FT-10, FT-14", uc="UC: Manage plans and point adjustments", status="Specified",
        purpose="Lets an Administrator define plans and the key products that activation keys grant (Premium days with "
                "examiner credits, or points).",
        nav_from=[("Main menu", "User clicks \"Plans\"")],
        nav_to=[("Activation Keys", "User clicks \"Generate keys\" on a product")],
        pre=[AUTH, ADMIN],
        entry=[("Main menu", "Any admin screen", "—")],
        exits=[("Save plan / product", "API 201", "Stay", "MSG-01"),
               ("Generate keys", "Any", "Activation Keys", "Product preselected"), ex_menu(), EX_SESSION],
        comps=[("TBL", "Plans", "Table", "—", "Code, name"),
               ("BTN", "New plan", "Button (Primary)", "—", "Opens form: code, name (required)"),
               ("TBL", "Key products", "Table", "—", "Code, name, type, points / days, plan, credits"),
               ("BTN", "New key product", "Button (Primary)", "—", "Opens form below"),
               ("RAD", "Type", "Radio group", "POINTS or PREMIUM", "Shows the matching fields"),
               ("NUM", "Points amount", "Number", "POINTS: ≥ 1 (BV-02); MSG-03", "—"),
               ("SEL", "Plan", "Select", "PREMIUM: required", "—"),
               ("NUM", "Premium days", "Number", "PREMIUM: ≥ 1; MSG-03", "—"),
               ("NUM", "Examiner credits", "Number", "PREMIUM: ≥ 1 (FT-14 BV-01); MSG-04", "—")],
        apis=[("Page load", "access.plans", "—", "Render plans", "Error → GLB-04"),
              ("Page load", "access.products", "—", "Render products", "Error → GLB-04"),
              ("Save plan", "access.createPlan", "`{code, name}`", "Toast MSG-01; reload", "400 → GLB-06; 409 → MSG-02"),
              ("Save product", "access.createProduct", "`{code, name, keyType, pointsAmount | planId, premiumDays, "
               "humanGradingCredits}`", "Toast MSG-01; reload", "400 → MSG-03/04; 409 → MSG-02")],
        interactions=[("Type-dependent fields", ["IF type = POINTS THEN show Points amount ELSE show Plan, Premium days, "
                                                 "Examiner credits", "END IF"])],
        msgs=[("Success Toast", "Saved", "\"Saved.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Code already used", "\"This code is already used.\"", "Below field"),
              ("Inline Error", "Amount/days < 1", "\"Enter a value of 1 or more.\"", "Below field"),
              ("Inline Error", "Credits < 1", "\"A Premium product needs at least 1 examiner grading.\"", "Below field")],
        rules=[("BR-08 / FT-10 BV-02", "Points and days ≥ 1", "MSG-03"), ("BR-08 / FT-14 BV-01", "Premium credits ≥ 1", "MSG-04")],
    ),
    # ------------------------------------------------------------------ Activation Keys
    screen(
        key="Keys", name="Activation Keys", route="/admin/access/keys · SALES_STAFF home", roles="ADMIN, SALES_STAFF",
        ft="FT-11", uc="UC: Generate and revoke activation keys",
        status="Specified for ADMIN (SALES_STAFF access and key list: Draft)",
        purpose="Lets staff generate a batch of activation keys for a key product, copy them once, and revoke keys "
                "that were lost before use.",
        nav_from=[("Login", "SALES_STAFF signs in (home)"), ("Plans & Key Products", "User clicks \"Generate keys\"")],
        nav_to=[("Plans & Key Products", "ADMIN clicks \"Back to products\"")],
        pre=[AUTH, role("ADMIN or SALES_STAFF"),
             ("SALES_STAFF access enabled on the API", "Continue", "Current release: show MSG-06 to SALES_STAFF")],
        entry=[("Generate keys", "Plans & Key Products", "Query: `?productId=`"), ("Home", "Login", "—")],
        exits=[("Generate", "API 201", "Stay (result panel)", "MSG-01"),
               ("User leaves while the result panel is open", "Keys not copied", "Selected screen", "Confirm MSG-02"),
               ex_menu(), EX_SESSION],
        comps=[("SEL", "Key product", "Select", "Required", "From access.products"),
               ("NUM", "Number of keys", "Number", "Required; 1–1,000 (BV-01); MSG-03", "Default: 10"),
               ("DAT", "Expires at", "Date-time picker", "Optional; future", "Empty = no expiry"),
               ("BTN", "Generate", "Button (Primary)", "—", "Triggers API 2"),
               ("PNL", "Generated keys", "Panel", "Shown once", "Raw keys list; \"Copy all\" and \"Download CSV\""),
               ("TBL", "Issued keys", "Table", "Draft (OQ-14)", "Hint (last 4), product, status ACTIVE / REDEEMED / "
                "REVOKED, expiry"),
               ("BTN", "Revoke", "Button (Danger)", "Only ACTIVE keys; confirm MSG-04", "Triggers API 3")],
        apis=[("Page load", "access.products", "—", "Fill product select", "Error → GLB-04"),
              ("User clicks Generate", "access.generate", "`{productId, count, expiresAt}`", "Show raw keys once · "
               "loading: button spinner", "400 → MSG-03; 403 → MSG-06"),
              ("User confirms Revoke", "access.revoke", "Path: `id`", "Row status REVOKED; toast MSG-05",
               "400 (REDEEMED) → MSG-07"),
              ("Page load [Draft]", "access.keyList", "Query: `productId, status, page`", "Render issued keys",
               "Draft")],
        interactions=[("Show once", ["The raw keys exist only in the generate response. The panel stays until the user "
                                     "copies or downloads them; leaving earlier asks for confirmation (MSG-02). The "
                                     "client never stores raw keys."])],
        msgs=[("Success Toast", "Keys generated", "\"{n} keys generated. Copy them now — they will not be shown again.\"",
               "Auto-dismiss 5s"),
              ("Confirm Modal", "Leaving with keys not copied", "Title: \"Leave without copying the keys?\" · Body: "
               "\"You will not be able to see these keys again.\"", "Buttons: \"Leave\" (Danger) + \"Stay\""),
              ("Inline Error", "Count outside 1–1,000", "\"Generate between 1 and 1,000 keys at a time.\"", "Below field"),
              ("Confirm Modal", "User clicks Revoke", "Title: \"Revoke this key?\" · Body: \"It can no longer be "
               "redeemed.\"", "Buttons: \"Revoke\" (Danger) + \"Cancel\""),
              ("Success Toast", "Revoked", "\"The key has been revoked.\"", "Auto-dismiss 3s"),
              ("Alert Banner", "SALES_STAFF in current release / 403", "\"Key management for Sales is not enabled yet. "
               "Please ask an administrator.\"", "Persistent"),
              ("Error Toast", "Revoke a REDEEMED key", "\"This key has already been redeemed and cannot be revoked.\"",
               "Auto-dismiss 5s")],
        rules=[("BR-07", "Redeemed keys cannot be revoked", "Revoke hidden for REDEEMED; MSG-07"),
               ("FT-11 BV-01", "1–1,000 keys per request", "MSG-03")],
    ),
    # ------------------------------------------------------------------ Points & Subscriptions
    screen(
        key="AdminAccounts", name="Points & Subscriptions", route="/admin/access/accounts", roles="ADMIN",
        ft="FT-10, FT-12, FT-14", uc="UC: Manage plans and point adjustments", status="Specified",
        purpose="Lets an Administrator grant subscription days and examiner credits, adjust or refund a learner's "
                "points with a reason, and consume an examiner credit.",
        nav_from=[("User Detail", "User clicks \"Manage points & subscription\""), ("Main menu", "User clicks "
                                                                                                "\"Points & subscriptions\"")],
        nav_to=[("User Detail", "User clicks the learner's name")],
        pre=[AUTH, ADMIN],
        entry=[("From user", "User Detail", "Query: `?userId=`"), ("Main menu", "Any admin screen", "—")],
        exits=[("Any action succeeds", "API 2xx", "Stay", "MSG-01"), ex_menu(), EX_SESSION],
        comps=[("TXT", "Learner", "User picker", "Required", "Search by email (from admin.users)"),
               ("SEL", "Plan", "Select", "Required for grant", "—"),
               ("NUM", "Days", "Number", "≥ 1 (FT-10 BV-01); MSG-02", "—"),
               ("NUM", "Examiner credits", "Number", "≥ 0", "—"),
               ("BTN", "Grant subscription", "Button (Primary)", "—", "Triggers API 1"),
               ("NUM", "Point change", "Number", "Non-zero integer (+ credit / − debit)", "—"),
               ("TXT", "Reason", "Text Input", "Required; MSG-03", "Stored in the ledger"),
               ("BTN", "Adjust points", "Button (Primary)", "Confirm MSG-04", "Triggers API 2"),
               ("BTN", "Refund", "Button (Secondary)", "Amount ≥ 1; reference of the debit", "Triggers API 3"),
               ("BTN", "Consume examiner credit", "Button (Secondary)", "—", "Triggers API 4")],
        apis=[("User clicks Grant subscription", "access.grant", "`{userId, planId, durationDays, humanGradingCredits}`",
               "Toast MSG-01", "400 → MSG-02"),
              ("User confirms Adjust points", "access.adjust", "`{userId, delta, reason, idempotencyKey}`",
               "Toast MSG-01", "400 → MSG-03; 402 → MSG-05; 409 → MSG-06"),
              ("User clicks Refund", "access.refund", "`{userId, amount, referenceType, referenceId, idempotencyKey, "
               "description}`", "Toast MSG-01", "409 → MSG-06"),
              ("User clicks Consume examiner credit", "access.consumeCredit", "Path: `userId`", "Credits left shown",
               "402 → MSG-07")],
        interactions=[("Idempotency", ["Each form generates an idempotencyKey when opened and reuses it on retry, so a "
                                       "double submit changes the balance once (BR-30)."])],
        msgs=[("Success Toast", "Action succeeded", "\"Done. The learner's balance and subscription are updated.\"",
               "Auto-dismiss 3s"),
              ("Inline Error", "Days < 1", "\"Grant at least 1 day.\"", "Below field"),
              ("Inline Error", "Reason missing", "\"Enter a reason for this change.\"", "Below field"),
              ("Confirm Modal", "Adjust points", "Title: \"Change balance by {delta}?\"", "Buttons: \"Confirm\" + \"Cancel\""),
              ("Error Toast", "402 balance too low", "\"The learner does not have enough points for this debit.\"",
               "Auto-dismiss 5s"),
              ("Error Toast", "409 idempotency conflict", "\"This change conflicts with an earlier request. Reload and try "
               "again.\"", "Auto-dismiss 5s"),
              ("Error Toast", "402 no credit", "\"The learner has no examiner credits left.\"", "Auto-dismiss 5s")],
        rules=[("BR-09", "Balance never below 0", "MSG-05"), ("BR-30", "Idempotency key", "Reused on retry; 409 → MSG-06"),
               ("BR-31", "Credit consumption needs a credit", "MSG-07")],
    ),
    # ------------------------------------------------------------------ Topics & Knowledge Points
    screen(
        key="AuthorTopics", name="Topics & Knowledge Points", route="/author/topics · CONTENT_AUTHOR home",
        roles="ADMIN, CONTENT_AUTHOR", ft="FT-15", uc="UC: Manage topics, knowledge points, questions, packages, "
                                                    "vocabulary and videos",
        status="Specified",
        purpose="Lets an author maintain the topic tree of each skill and the knowledge points each topic teaches.",
        nav_from=[("Login", "CONTENT_AUTHOR signs in (home)"), ("Main menu", "User clicks \"Topics\"")],
        nav_to=[("Question Bank", "User clicks \"Questions\" on a knowledge point"),
                ("Packages", "User clicks \"Packages\" on a topic"),
                ("Lesson Builder", "User clicks a lesson [Draft]")],
        pre=[AUTH, AUTHOR],
        entry=[("Home", "Login", "—"), ("Main menu", "Any author screen", "Query: `?skill=`")],
        exits=[("Save topic / KP", "API 2xx", "Stay", "MSG-01"), ex_menu("GLB-07 if unsaved"), EX_SESSION],
        comps=[("TBL", "Topic tree", "Tree", "Grouped by skill; ordered by sortOrder", "Code, name, band range, status"),
               ("TXT", "Code", "Text Input", "Required; ≤ 100 chars; read-only after create", "—"),
               ("TXT", "Name", "Text Input", "Required; ≤ 255 chars", "—"),
               ("SEL", "Skill", "Select", "LISTENING, READING, WRITING, SPEAKING", "Disabled once the topic has "
                "published lessons (MSG-03)"),
               ("SEL", "Parent topic", "Select", "Optional", "—"),
               ("NUM", "Band min / max", "Number (0.5)", "0.0–9.0; min ≤ max; MSG-04", "—"),
               ("NUM", "Sort order", "Number", "Integer", "—"),
               ("SEL", "Status", "Select", "Topic status (update only)", "—"),
               ("BTN", "Save topic", "Button (Primary)", "—", "Create or update"),
               ("TBL", "Knowledge points", "Table", "Filtered by topic", "Code, name, kind, skill"),
               ("BTN", "New knowledge point", "Button (Secondary)", "Code ≤ 100, name ≤ 255", "Fields: code, name, kind, "
                "learning type, skill, description")],
        apis=[("Page load", "content.topics", "—", "Render tree · loading: skeleton", "403 → GLB-02"),
              ("User selects a topic", "content.topic", "Path: `id`", "Fill form", "404 → GLB-03"),
              ("Save new topic", "content.createTopic", "`{parentTopicId, code, name, sortOrder, bandMin, bandMax, skill}`",
               "Toast MSG-01; reload tree", "400 → MSG-04; 409 → MSG-02"),
              ("Save existing topic", "content.updateTopic", "`{parentTopicId, name, sortOrder, status, bandMin, bandMax, "
               "skill}` (skill omitted when unchanged)", "Toast MSG-01", "409 TOPIC_SKILL_LOCKED → MSG-03"),
              ("Topic selected", "content.kps", "Query: `topicId`", "Render KPs", "—"),
              ("Save KP", "content.createKp", "`{topicId, code, name, kind, learningType, skill, description}`",
               "Toast MSG-01", "400 → GLB-06")],
        interactions=[("Skill lock", ["IF the topic has published lessons THEN disable Skill with tooltip MSG-03",
                                      "Sending no skill on update keeps the current skill (FT-15/AC-02).", "END IF"])],
        msgs=[("Success Toast", "Saved", "\"Saved.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Duplicate code", "\"This code is already used.\"", "Below field"),
              ("Inline Error", "409 TOPIC_SKILL_LOCKED", "\"The skill cannot change because this topic has published "
               "lessons.\"", "Below field"),
              ("Inline Error", "Band outside 0–9 or min > max", "\"Use a band range between 0.0 and 9.0.\"", "Below field")],
        rules=[("BR-12", "One skill per topic; locked after lessons are published", "MSG-03"), AUTHOR_RULE],
    ),
    # ------------------------------------------------------------------ Question Bank
    screen(
        key="QuestionBank", name="Question Bank", route="/author/questions", roles="ADMIN, CONTENT_AUTHOR",
        ft="FT-16", uc="UC: Manage topics, knowledge points, questions, packages, vocabulary and videos",
        status="Specified",
        purpose="Lets an author create versioned questions with answer, explanation, hint, purpose and knowledge "
                "points, and filter the bank by purpose and skill.",
        nav_from=[("Topics & Knowledge Points", "User clicks \"Questions\""), ("Main menu", "User clicks \"Questions\"")],
        nav_to=[("Packages", "User adds selected questions to a package")],
        pre=[AUTH, AUTHOR],
        entry=[("Main menu", "Any author screen", "Query: `?purpose=&skill=`")],
        exits=[("Save", "API 2xx", "Stay", "MSG-01"), ex_menu("GLB-07 if the editor has unsaved changes"), EX_SESSION],
        comps=[("SEL", "Purpose filter", "Select", "All, LEARNING, EXAM", "Sent to the API (database filter)"),
               ("SEL", "Skill filter", "Select", "All + four skills", "Sent to the API"),
               ("TBL", "Questions", "Table", "—", "Type, stem excerpt, purpose, skill, current version, status"),
               ("BTN", "New question", "Button (Primary)", "—", "Type, skill, access level, purpose (default LEARNING)"),
               ("SEL", "Question type", "Select", "MULTIPLE_CHOICE, FILL_IN_BLANK, MATCHING, TRUE_FALSE_NOT_GIVEN, "
                "SHORT_ANSWER, ESSAY, SPEAKING", "Fixed after create"),
               ("RAD", "Purpose", "Radio group", "LEARNING / EXAM; fixed after create", "—"),
               ("TXA", "Stem", "Rich text", "Required", "Version editor"),
               ("TBL", "Options", "Editable list", "Choice types only", "Key, content, order"),
               ("TXA", "Answer specification", "JSON / form", "Required", "Hidden from learners"),
               ("TXA", "Explanation", "Text Area", "—", "—"),
               ("TXT", "Hint", "Text Input", "≤ 500 chars (BV-01); MSG-03", "Shown after a wrong answer"),
               ("SEL", "Difficulty", "Select", "Question difficulty", "—"),
               ("SEL", "Knowledge points", "Multi-select", "≥ 1 recommended", "With weight / primary flag"),
               ("BTN", "Save version", "Button (Primary)", "Version number ≥ 1 (next number suggested)", "—"),
               ("BTN", "Archive", "Button (Danger)", "Confirm MSG-04", "—")],
        apis=[("Page load / filter change", "content.questions", "Query: `skill, purpose`", "Render table", "403 → GLB-02"),
              ("Row selected", "content.question", "Path: `id`", "Fill editor with versions", "404 → GLB-03"),
              ("New question", "content.createQuestion", "`{questionType, skill, accessLevel, purpose}`",
               "Open version editor", "400 → MSG-02"),
              ("Save version", "content.addQuestionVersion", "`{versionNumber, stem, options, answerSpecJson, "
               "explanation, hint, difficulty, knowledgePoints}`", "Toast MSG-01", "400 → MSG-03 / GLB-06"),
              ("Confirm Archive", "content.archiveQuestion", "Path: `id`", "Row status ARCHIVED", "—"),
              ("Editor open", "content.kps", "—", "Fill KP selector", "—")],
        interactions=[("Purpose", ["Purpose is chosen once at creation; new versions keep it (FT-16/AC-02). The editor "
                                   "shows it read-only after creation."])],
        msgs=[("Success Toast", "Saved", "\"Question saved.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Invalid purpose / type", "\"Choose a valid purpose and type.\"", "Below field"),
              ("Inline Error", "Hint too long", "\"Keep the hint under 500 characters.\"", "Below field"),
              ("Confirm Modal", "Archive", "Title: \"Archive this question?\" · Body: \"It stays in published packages but "
               "cannot be added to new ones.\"", "Buttons: \"Archive\" (Danger) + \"Cancel\"")],
        rules=[("BR-14", "Purpose fixed: LEARNING or EXAM", "Read-only after create"), AUTHOR_RULE,
               ("FT-16 BV-01", "Hint ≤ 500 chars", "MSG-03")],
    ),
    # ------------------------------------------------------------------ Packages
    screen(
        key="Packages", name="Packages", route="/author/packages", roles="ADMIN, CONTENT_AUTHOR",
        ft="FT-17, FT-34, FT-35", uc="UC: Manage topics, knowledge points, questions, packages, vocabulary and videos",
        status="Specified (TOPIC_TEST creation: Draft)",
        purpose="Lets an author group questions into versioned packages — practice sets, tests and quizzes — and "
                "publish them after the system checks question ownership and purpose.",
        nav_from=[("Topics & Knowledge Points", "User clicks \"Packages\""), ("Question Bank", "Add to package")],
        nav_to=[("Question Bank", "User clicks \"Add questions\"")],
        pre=[AUTH, AUTHOR],
        entry=[("Main menu", "Any author screen", "Query: `?status=&accessLevel=`")],
        exits=[("Publish", "API 200", "Stay", "MSG-01"), ("Publish rejected", "422", "Stay", "MSG-02…04"), ex_menu(),
               EX_SESSION],
        comps=[("SEL", "Filters", "Select", "Access level, status", "Sent to the API"),
               ("TBL", "Packages", "Table", "—", "Code, title, type, access, published version"),
               ("BTN", "New package", "Button (Primary)", "—", "Code ≤ 100, title ≤ 255, type, access level"),
               ("SEL", "Package type", "Select", "PRACTICE_SET, MOCK_TEST, PLACEMENT_TEST, QUIZ, LESSON (TOPIC_TEST: "
                "Draft)", "—"),
               ("SEL", "Linked lesson", "Select", "PRACTICE_SET only", "Lesson of the same skill"),
               ("BTN", "New version", "Button (Secondary)", "Version number ≥ 1", "Starts DRAFT"),
               ("PNL", "Sections", "Editable list", "Title, skill, order, time limit, instructions", "Questions per section"),
               ("BTN", "Publish", "Button (Primary)", "Confirm MSG-05", "Triggers publish checks")],
        apis=[("Page load / filters", "content.packages", "Query: `accessLevel, status`", "Render table", "403 → GLB-02"),
              ("Row selected", "content.package", "Path: `id`", "Render versions and sections", "404 → GLB-03"),
              ("Create package", "content.createPackage", "`{code, title, packageType, accessLevel, lessonId}`",
               "Toast MSG-06", "422 INVALID_PACKAGE_LESSON → MSG-04"),
              ("New version", "content.addPackageVersion", "`{versionNumber, rulesJson}`", "Version DRAFT", "400 → GLB-06"),
              ("Add section", "content.addSection", "`{title, skill, sortOrder, timeLimitSeconds, instructions}`",
               "Section added", "400 → GLB-06"),
              ("User confirms Publish", "content.publish", "`{versionId}`", "Status PUBLISHED; toast MSG-01",
               "422 QUESTION_ALREADY_USED → MSG-02; 422 QUESTION_PURPOSE_MISMATCH → MSG-03; 422 INVALID_PACKAGE_LESSON "
               "→ MSG-04")],
        interactions=[("Publish conflicts", ["QUESTION_ALREADY_USED lists at most 10 conflicting questions; the screen "
                                             "shows them as links to the Question Bank. Nothing is saved or published "
                                             "when any check fails."])],
        msgs=[("Success Toast", "Published", "\"Version {n} is published.\"", "Auto-dismiss 3s"),
              ("Alert Banner", "422 QUESTION_ALREADY_USED", "\"Some questions already belong to another lesson or package: "
               "{list}. Remove them or create new questions.\"", "Persistent"),
              ("Alert Banner", "422 QUESTION_PURPOSE_MISMATCH", "\"Mock and placement tests need EXAM questions; lessons, "
               "practice sets and topic tests need LEARNING questions.\"", "Persistent"),
              ("Alert Banner", "422 INVALID_PACKAGE_LESSON", "\"The linked lesson does not exist or teaches another skill.\"",
               "Persistent"),
              ("Confirm Modal", "Publish", "Title: \"Publish version {n}?\" · Body: \"Learners will see it. Learners who "
               "already started keep their version.\"", "Buttons: \"Publish\" + \"Cancel\""),
              ("Success Toast", "Package created", "\"Package created.\"", "Auto-dismiss 3s")],
        rules=[("BR-13", "One owner per question", "MSG-02"), ("BR-14", "Purpose fits the package type", "MSG-03"),
               AUTHOR_RULE],
    ),
    # ------------------------------------------------------------------ Media Assets
    screen(
        key="Assets", name="Media Assets", route="/author/assets", roles="ADMIN, CONTENT_AUTHOR",
        ft="FT-18, FT-24", uc="UC: Manage topics, knowledge points, questions, packages, vocabulary and videos; Upload media", status="Specified (upload: Draft)",
        purpose="Lets an author register passage text, images and Listening audio as assets and link them to "
                "sections or question versions.",
        nav_from=[("Packages", "User clicks \"Add asset\" on a section"), ("Main menu", "User clicks \"Assets\"")],
        nav_to=[("Packages", "Asset linked; user returns")],
        pre=[AUTH, AUTHOR],
        entry=[("Add asset", "Packages", "Query: `?sectionId=` or `?questionVersionId=`")],
        exits=[("Save / link", "API 2xx", "Stay or Packages", "MSG-01"), ex_menu(), EX_SESSION],
        comps=[("SEL", "Asset type", "Select", "Text, image, audio (AssetType)", "—"),
               ("TXA", "Text content / transcript", "Text Area", "—", "Transcripts are revealed to learners only after "
                "they earn them"),
               ("TXT", "Media reference", "Text Input", "https:// URL, PNG/JPEG/SVG data URI, or audio key (ASCII, no "
                "leading '/', no '..'); MSG-02", "—"),
               ("NUM", "Duration (s)", "Number", "Audio only", "—"),
               ("BTN", "Upload file", "File picker", "Draft; size [TBC]", "Uploads to Media Storage, fills the reference"),
               ("BTN", "Save asset", "Button (Primary)", "—", "Triggers API 1"),
               ("BTN", "Link", "Button (Secondary)", "Section or question version + order", "Triggers API 2"),
               ("PNL", "Preview", "Panel", "—", "Image / audio player from the built URL")],
        apis=[("User clicks Save asset", "content.createAsset", "`{assetType, textContent, mediaReference, "
               "durationSeconds, checksum}`", "Toast MSG-01", "400 / INVALID_MEDIA_REFERENCE → MSG-02"),
              ("User clicks Link", "content.linkAsset", "`{assetId, sectionId | questionVersionId, sortOrder}`",
               "Toast MSG-01", "400 → GLB-06"),
              ("User opens an asset", "content.asset", "Path: `id`", "Fill form", "404 → GLB-03"),
              ("User picks a file [Draft]", "content.upload", "multipart file [TBC]", "Reference filled", "Too large → MSG-03")],
        interactions=[("Reference check", ["The client applies the same pattern as the server before saving, so an "
                                           "http:// URL or a path with '..' is caught in the form (FT-18/NAC-01)."])],
        msgs=[("Success Toast", "Saved / linked", "\"Asset saved.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Invalid reference", "\"Use an https:// link, a PNG, JPEG or SVG image, or a valid audio "
               "key.\"", "Below field"),
              ("Inline Error", "File too large [Draft]", "\"Files must be smaller than {size} MB.\"", "Below field")],
        rules=[("BR-19", "Transcripts hidden until earned", "Note under the transcript field"), AUTHOR_RULE],
    ),
    # ------------------------------------------------------------------ Lesson Builder
    screen(
        key="LessonBuilder", name="Lesson Builder", route="/author/lessons/:lessonId", roles="ADMIN, CONTENT_AUTHOR",
        ft="FT-19", uc="UC: Author lessons", status="Draft",
        draft="Draft: there is no lesson authoring API in the current release; lessons come from seed data and are "
              "validated when read. API rows are [TBC] (OQ-13).",
        purpose="Lets an author build a topic's ordered lessons from theory, assets, exercise blocks and essay blocks, "
                "and publish them to the learning path.",
        nav_from=[("Topics & Knowledge Points", "User clicks a lesson or \"New lesson\"")],
        nav_to=[("Topics & Knowledge Points", "User clicks \"Back\""), ("Media Assets", "User adds an asset")],
        pre=[AUTH, AUTHOR],
        entry=[("Lesson link", "Topics & Knowledge Points", "`lessonId` or Query: `?topicId=` (new)")],
        exits=[("Publish", "Valid", "Stay", "MSG-01"), ("Publish rejected", "INVALID_LESSON_BLOCK", "Stay", "MSG-02"),
               ex_menu("GLB-07 if unsaved"), EX_SESSION],
        comps=[("TXT", "Title / code / summary", "Text Inputs", "Required", "Skill inherited from the topic (read-only)"),
               ("TBL", "Blocks", "Drag-and-drop list", "Ordered", "Theory, asset, exercise, essay"),
               ("TXA", "Theory text", "Rich text", "—", "Tagged with knowledge points"),
               ("SEL", "Exercise questions", "Question picker", "Same skill; LEARNING; unused elsewhere", "—"),
               ("SEL", "Essay question", "Question picker", "Exactly one ESSAY question", "—"),
               ("TXA", "Task 1 chart facts", "Text Area", "1–2,000 chars; required with ≥ 1 image for Task 1; MSG-03",
                "Never shown to learners"),
               ("NUM", "Essay pass band", "Number (0.5)", "0–9", "—"),
               ("BTN", "Publish lesson", "Button (Primary)", "Topic with a final test needs ≥ 1 practice set", "—")],
        apis=[("Page load / save / publish [Draft]", "content.lessons", "Lesson and blocks [TBC]", "Toast MSG-01",
               "INVALID_LESSON_BLOCK → MSG-02")],
        interactions=[("Block order", ["Dragging a block updates sortOrder for every block below it; one save sends the "
                                       "whole order [TBC]."])],
        msgs=[("Success Toast", "Published", "\"Lesson published. Learners will see it in the topic.\"", "Auto-dismiss 3s"),
              ("Alert Banner", "INVALID_LESSON_BLOCK", "\"An essay block needs exactly one essay question; a Task 1 essay "
               "also needs chart facts and an image.\"", "Persistent"),
              ("Inline Error", "Chart facts invalid", "\"Enter the chart facts (up to 2,000 characters).\"", "Below field")],
        rules=[("BR-12", "Lesson inherits the topic's skill", "Skill read-only"),
               ("BR-13", "A question has one owner", "Picker hides used questions")],
    ),
    # ------------------------------------------------------------------ Vocabulary Management
    screen(
        key="AuthorVocabulary", name="Vocabulary Management", route="/author/vocabulary", roles="ADMIN, CONTENT_AUTHOR",
        ft="FT-36", uc="UC: Manage topics, knowledge points, questions, packages, vocabulary and videos",
        status="Specified",
        purpose="Lets an author add vocabulary items and their senses to the catalog used by lessons, videos, "
                "flashcards and games.",
        nav_from=[("Main menu", "User clicks \"Vocabulary\" (author area)")],
        nav_to=[("Video Management", "User links a sense to a video segment")],
        pre=[AUTH, AUTHOR],
        entry=[("Main menu", "Any author screen", "—")],
        exits=[("Save", "API 201", "Stay", "MSG-01"), ex_menu(), EX_SESSION],
        comps=[("TXT", "Search", "Search Input", "—", "Same search as learners"),
               ("TXT", "Lemma", "Text Input", "Required; ≤ 255 chars (BV-01); MSG-02", "—"),
               ("TXT", "IPA", "Text Input", "Optional", "—"),
               ("TXT", "Pronunciation audio", "Text Input", "Media reference", "—"),
               ("SEL", "Part of speech", "Select", "NOUN, VERB, ADJECTIVE, ADVERB, PREPOSITION, CONJUNCTION, IDIOM, "
                "PHRASAL_VERB", "Sense form"),
               ("TXA", "English definition / Vietnamese meaning / example", "Text Areas", "—", "Sense form"),
               ("BTN", "Save item / Add sense", "Button (Primary)", "—", "—")],
        apis=[("Search", "vocab.search", "Query: `query`", "Render results", "—"),
              ("Select item", "vocab.get", "Path: `id`", "Render senses", "404 → GLB-03"),
              ("Save item", "vocab.create", "`{lemma, ipa, pronunciationAudioReference}`", "Toast MSG-01", "400 → MSG-02"),
              ("Add sense", "vocab.addSense", "`{partOfSpeech, englishDefinition, vietnameseMeaning, exampleSentence, "
               "imageUrl, sortOrder}`", "Toast MSG-01", "400 → GLB-06")],
        interactions=[("Duplicates", ["Before saving, the screen searches the lemma and warns when it already exists "
                                      "(MSG-03); saving is still allowed for homographs."])],
        msgs=[("Success Toast", "Saved", "\"Saved.\"", "Auto-dismiss 3s"),
              ("Inline Error", "Lemma invalid", "\"Enter a word of up to 255 characters.\"", "Below field"),
              ("Warning Toast", "Lemma exists", "\"This word is already in the catalog. Add a sense to it instead?\"",
               "Auto-dismiss 5s")],
        rules=[AUTHOR_RULE],
    ),
    # ------------------------------------------------------------------ Video Management
    screen(
        key="AuthorVideos", name="Video Management", route="/author/videos", roles="ADMIN, CONTENT_AUTHOR",
        ft="FT-37", uc="UC: Manage topics, knowledge points, questions, packages, vocabulary and videos",
        status="Specified",
        purpose="Lets an author register a YouTube learning video, split it into timed segments with transcripts and "
                "linked words, and publish it.",
        nav_from=[("Main menu", "User clicks \"Videos\" (author area)")],
        nav_to=[("Vocabulary Management", "User creates a missing word")],
        pre=[AUTH, AUTHOR],
        entry=[("Main menu", "Any author screen", "—")],
        exits=[("Save / publish", "API 2xx", "Stay", "MSG-01"), ex_menu("GLB-07 if unsaved"), EX_SESSION],
        comps=[("TBL", "Videos", "Table", "Filter by access level, status", "Title, level, status"),
               ("TXT", "YouTube URL / id", "Text Input", "Required", "Thumbnail preview"),
               ("TXT", "Title / description", "Text Inputs", "Title required", "—"),
               ("SEL", "Topic", "Select", "Checked with content (2 s connect, 5 s read)", "MSG-02 when unreachable"),
               ("SEL", "Level", "Select", "A2, B1, B2, C1, C2", "—"),
               ("SEL", "Access level", "Select", "FREE, PREMIUM", "—"),
               ("TBL", "Segments", "Editable list", "Sequence ≥ 1; start/end ≥ 0 ms; MSG-03", "Transcript, Vietnamese "
                "translation"),
               ("TBL", "Lexical entries", "List", "Span start/end char", "Link to a vocabulary sense"),
               ("BTN", "Publish", "Button (Primary)", "—", "—")],
        apis=[("Page load", "video.list", "Query: `accessLevel, status`", "Render table", "—"),
              ("Select video", "video.get", "Path: `id`", "Fill editor", "404 → GLB-03"),
              ("Save video", "video.create", "`{youtubeVideoId, youtubeUrl, title, description, thumbnailUrl, "
               "durationSeconds, topicId, level, accessLevel}`", "Toast MSG-01", "503 → MSG-02; 400 → GLB-06"),
              ("Add segment", "video.addSegment", "`{sequenceNo, startMs, endMs, transcript, translationVi}`",
               "Row added", "400 → MSG-03"),
              ("Add lexical entry", "video.addLexical", "`{vocabularySenseId, surfaceText, startChar, endChar, sortOrder}`",
               "Highlight added", "400 → GLB-06"),
              ("Publish", "video.publish", "Path: `id`", "Status PUBLISHED; toast MSG-04", "—")],
        interactions=[("Segment timing", ["The editor sorts segments by sequenceNo and warns when end ≤ start or segments "
                                          "overlap [TBC: server rule]."])],
        msgs=[("Success Toast", "Saved", "\"Video saved.\"", "Auto-dismiss 3s"),
              ("Alert Banner", "503 topic check failed", "\"We could not verify the topic right now. Please try again.\"",
               "Persistent"),
              ("Inline Error", "Segment invalid", "\"Sequence starts at 1 and times cannot be negative.\"", "Below row"),
              ("Success Toast", "Published", "\"Video published.\"", "Auto-dismiss 3s")],
        rules=[AUTHOR_RULE, ("FT-37 BV-01/02", "Sequence ≥ 1; times ≥ 0 ms", "MSG-03")],
    ),
    # ------------------------------------------------------------------ Grading Workspace
    screen(
        key="Grading", name="Grading Workspace", route="/examiner/grading · EXAMINER home", roles="ADMIN, EXAMINER",
        ft="FT-32, FT-52", uc="UC: Grade attempt manually and finalize result",
        status="Specified (work queue and response view: Draft)",
        purpose="Lets an Examiner open a submitted attempt, enter item scores, errors and knowledge-point judgments, and "
                "finalize the result so it reaches the learner's progress.",
        nav_from=[("Login", "EXAMINER signs in (home)"), ("Main menu", "User clicks \"Grading\"")],
        nav_to=[("Grading Workspace (next attempt)", "Result finalized; user clicks \"Next\"")],
        pre=[AUTH, role("ADMIN or EXAMINER")],
        entry=[("Home", "Login", "—"), ("Attempt link", "Shared by staff", "Query: `?attemptId=`")],
        exits=[("Finalize", "API 200", "Stay (queue)", "MSG-01"), ex_menu("GLB-07 if details unsaved"), EX_SESSION],
        comps=[("TBL", "Waiting attempts", "Table", "Draft (OQ-12)", "Learner, test, submitted at"),
               ("TXT", "Attempt id", "Text Input", "UUID", "Current release: examiner pastes the attempt id"),
               ("PNL", "Learner responses", "Panel", "Draft: read API [TBC]", "Per item: prompt, response, max score"),
               ("NUM", "Item score", "Number", "0 to the item's max (BV-02); MSG-03", "Per item"),
               ("TBL", "Errors", "Editable list", "Error type ≤ 50 chars (BV-03)", "Per item; optional knowledge point"),
               ("SEL", "Knowledge-point judgment", "Select", "Only KPs snapshotted on the item", "Correct / incorrect"),
               ("NUM", "Overall band", "Number (0.5)", "0.0–9.0 (BV-01); MSG-04", "—"),
               ("BTN", "Open result version", "Button (Primary)", "—", "Triggers API 1"),
               ("BTN", "Save details", "Button (Secondary)", "—", "Triggers API 2"),
               ("BTN", "Finalize", "Button (Primary)", "Confirm MSG-05", "Triggers API 3")],
        apis=[("User clicks Open result version", "as.openVersion", "Path: `attemptId`; `{overallBand}`",
               "Returns the result version id; editor opens", "400 (not submitted / latest DRAFT or PROCESSING) → MSG-02; "
               "403 → GLB-02"),
              ("User clicks Save details", "as.saveDetails", "`{overallBand, skillScores, itemResults, errors, "
               "knowledgeJudgments}`", "Toast MSG-06", "400 → MSG-03 / MSG-04"),
              ("User confirms Finalize", "as.finalize", "Path: `resultId`", "Result COMPLETED; event written once; "
               "toast MSG-01", "Finalizing again returns the same result (no second event)"),
              ("Page load [Draft]", "as.queue", "—", "Render waiting attempts", "Draft")],
        interactions=[("Re-grade", ["Opening a version for a COMPLETED attempt creates the next version; once finalized, "
                                    "the learner's evidence is replaced by the new version (BR-25)."])],
        msgs=[("Success Toast", "Finalized", "\"Result finalized. The learner will be notified.\"", "Auto-dismiss 3s"),
              ("Error Toast", "Cannot open a version", "\"This attempt is not ready for grading, or another grading is "
               "still open.\"", "Auto-dismiss 5s"),
              ("Inline Error", "Score above max / foreign item / KP", "\"Enter a score from 0 to {max} for this item.\"",
               "Below field"),
              ("Inline Error", "Band outside 0–9", "\"Enter a band from 0.0 to 9.0.\"", "Below field"),
              ("Confirm Modal", "Finalize", "Title: \"Finalize this result?\" · Body: \"The learner sees the result and "
               "their progress is updated.\"", "Buttons: \"Finalize\" + \"Cancel\""),
              ("Success Toast", "Details saved", "\"Grading saved.\"", "Auto-dismiss 3s")],
        rules=[("BR-26", "Only EXAMINER and ADMIN grade; finalizing twice has no effect", "Route guarded; repeat finalize "
                "is harmless"),
               ("BR-25", "Newer version replaces older evidence", "Re-grade note"),
               ("FT-32 BV-01…03", "Band 0–9; score ≤ max; error type ≤ 50", "Inline errors")],
    ),
]
