spring:
  datasource:
    url: ${ASSESSMENT_DB_URL:jdbc:postgresql://localhost:5432/assessment_db}
    username: ${ASSESSMENT_DB_USERNAME:postgres}
    password: ${ASSESSMENT_DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

app:
  auth:
    internal-jwt-issuer: ${INTERNAL_JWT_ISSUER:urn:code-base:api-gateway}
    internal-jwt-secret: ${GATEWAY_INTERNAL_JWT_SECRET:HK5r8WcYA8J8jo2ruIBCEXRcHhUfSDUqP16H29P1sxo=}
  security:
    public-endpoints:
      - method: GET
        patterns:
          - /actuator/health
          - /actuator/info

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      probes:
        enabled: true

